In [2]:
!pip install psutil

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://packagefeedproxy.microsoft.io/pypi/simple/


In [3]:
import psutil

cpu_usage = psutil.cpu_percent(interval=1)

print(f"CPU Usage: {cpu_usage}%")

CPU Usage: 43.6%


In [4]:
import psutil
import time

while True:
    cpu_usage = psutil.cpu_percent(interval=1)
    print(f"CPU Usage: {cpu_usage}%")
    time.sleep(1)

CPU Usage: 50.6%
CPU Usage: 30.8%


KeyboardInterrupt: 

In [5]:
import psutil
import time

while True:

    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()
    frequency = psutil.cpu_freq()

    print("------ SYSTEM STATUS ------")
    print(f"CPU Usage      : {cpu}%")
    print(f"CPU Frequency  : {frequency.current / 1000:.2f} GHz")
    print(f"CPU Cores      : {psutil.cpu_count(logical=False)}")
    print(f"Logical CPUs   : {psutil.cpu_count(logical=True)}")
    print(f"Memory Usage   : {memory.percent}%")
    print(f"Memory Used    : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Total   : {memory.total / (1024**3):.2f} GB")

    print("---------------------------")
    time.sleep(2)

------ SYSTEM STATUS ------
CPU Usage      : 37.9%
CPU Frequency  : 2.79 GHz
CPU Cores      : 8
Logical CPUs   : 16
Memory Usage   : 43.8%
Memory Used    : 27.98 GB
Memory Total   : 63.95 GB
---------------------------
------ SYSTEM STATUS ------
CPU Usage      : 33.9%
CPU Frequency  : 2.79 GHz
CPU Cores      : 8
Logical CPUs   : 16
Memory Usage   : 43.8%
Memory Used    : 27.99 GB
Memory Total   : 63.95 GB
---------------------------
------ SYSTEM STATUS ------
CPU Usage      : 40.0%
CPU Frequency  : 2.79 GHz
CPU Cores      : 8
Logical CPUs   : 16
Memory Usage   : 43.6%
Memory Used    : 27.86 GB
Memory Total   : 63.95 GB
---------------------------


KeyboardInterrupt: 

In [6]:
import psutil

cpu_per_core = psutil.cpu_percent(interval=1, percpu=True)

for cpu_number, usage in enumerate(cpu_per_core):
    print(f"CPU {cpu_number}: {usage}%")

CPU 0: 53.0%
CPU 1: 32.8%
CPU 2: 65.2%
CPU 3: 49.2%
CPU 4: 62.7%
CPU 5: 35.9%
CPU 6: 50.0%
CPU 7: 29.7%
CPU 8: 53.1%
CPU 9: 35.9%
CPU 10: 53.1%
CPU 11: 43.1%
CPU 12: 48.4%
CPU 13: 37.5%
CPU 14: 43.8%
CPU 15: 40.6%


In [7]:
import psutil
import time
from datetime import datetime

while True:

    cpu = psutil.cpu_percent(interval=1)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    result = f"{timestamp} | CPU Usage: {cpu}%"

    print(result)

    with open("cpu_monitor.log", "a") as file:
        file.write(result + "\n")

    time.sleep(5)

2026-08-30 00:59:07 | CPU Usage: 32.9%
2026-08-30 00:59:13 | CPU Usage: 38.7%


KeyboardInterrupt: 

Yes. For Python on Windows, the easiest approach is the `psutil` library.

First install it:

```powershell
pip install psutil
```

### 1. Simple CPU usage check

```python
import psutil

cpu_usage = psutil.cpu_percent(interval=1)

print(f"CPU Usage: {cpu_usage}%")
```

Example:

```text
CPU Usage: 33.2%
```

### 2. Continuously monitor CPU

This is useful if you want to watch CPU like Task Manager:

```python
import psutil
import time

while True:
    cpu_usage = psutil.cpu_percent(interval=1)
    print(f"CPU Usage: {cpu_usage}%")
    time.sleep(1)
```

Output:

```text
CPU Usage: 31.4%
CPU Usage: 34.7%
CPU Usage: 42.1%
CPU Usage: 28.9%
```

Stop it with **Ctrl+C**.

### 3. CPU + memory + CPU frequency

For your machine, I'd use this version:

```python
import psutil
import time

while True:

    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()
    frequency = psutil.cpu_freq()

    print("------ SYSTEM STATUS ------")
    print(f"CPU Usage      : {cpu}%")
    print(f"CPU Frequency  : {frequency.current / 1000:.2f} GHz")
    print(f"CPU Cores      : {psutil.cpu_count(logical=False)}")
    print(f"Logical CPUs   : {psutil.cpu_count(logical=True)}")
    print(f"Memory Usage   : {memory.percent}%")
    print(f"Memory Used    : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Total   : {memory.total / (1024**3):.2f} GB")

    print("---------------------------")
    time.sleep(2)
```

You should get something similar to:

```text
------ SYSTEM STATUS ------
CPU Usage      : 33.4%
CPU Frequency  : 3.47 GHz
CPU Cores      : 8
Logical CPUs   : 16
Memory Usage   : 48.2%
Memory Used    : 30.9 GB
Memory Total   : 64.0 GB
---------------------------
```

### 4. See CPU usage for every logical processor

```python
import psutil

cpu_per_core = psutil.cpu_percent(interval=1, percpu=True)

for cpu_number, usage in enumerate(cpu_per_core):
    print(f"CPU {cpu_number}: {usage}%")
```

Example:

```text
CPU 0: 32%
CPU 1: 15%
CPU 2: 48%
CPU 3: 27%
...
CPU 15: 35%
```

### 5. Save CPU usage to a log file

Since this can be useful for troubleshooting CPU spikes:

```python
import psutil
import time
from datetime import datetime

while True:

    cpu = psutil.cpu_percent(interval=1)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    result = f"{timestamp} | CPU Usage: {cpu}%"

    print(result)

    with open("cpu_monitor.log", "a") as file:
        file.write(result + "\n")

    time.sleep(5)
```

Your `cpu_monitor.log` will look like:

```text
2026-08-30 00:45:01 | CPU Usage: 31.2%
2026-08-30 00:45:07 | CPU Usage: 34.5%
2026-08-30 00:45:13 | CPU Usage: 52.7%
2026-08-30 00:45:19 | CPU Usage: 28.3%
```

For troubleshooting, the next useful improvement is to have Python automatically record **which process caused a CPU spike whenever CPU exceeds, for example, 80%**.

In [8]:
import psutil

memory = psutil.virtual_memory()

print(f"Total     : {memory.total / (1024**3):.2f} GB")
print(f"Used      : {memory.used / (1024**3):.2f} GB")
print(f"Available : {memory.available / (1024**3):.2f} GB")
print(f"Usage     : {memory.percent}%")

Total     : 63.95 GB
Used      : 28.51 GB
Available : 35.44 GB
Usage     : 44.6%


In [9]:
import psutil
import time

while True:

    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()

    print("\n===== SYSTEM STATUS =====")

    print(f"CPU Usage       : {cpu}%")
    print(f"Memory Usage    : {memory.percent}%")
    print(f"Memory Used     : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Available: {memory.available / (1024**3):.2f} GB")
    print(f"Memory Total    : {memory.total / (1024**3):.2f} GB")

    time.sleep(2)


===== SYSTEM STATUS =====
CPU Usage       : 65.2%
Memory Usage    : 44.9%
Memory Used     : 28.72 GB
Memory Available: 35.23 GB
Memory Total    : 63.95 GB

===== SYSTEM STATUS =====
CPU Usage       : 48.7%
Memory Usage    : 44.8%
Memory Used     : 28.68 GB
Memory Available: 35.27 GB
Memory Total    : 63.95 GB


KeyboardInterrupt: 

In [10]:
import psutil

processes = []

for process in psutil.process_iter(
    ['pid', 'name', 'memory_info']
):
    try:
        memory_gb = process.info['memory_info'].rss / (1024**3)

        processes.append(
            (
                process.info['pid'],
                process.info['name'],
                memory_gb
            )
        )

    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass


processes.sort(key=lambda x: x[2], reverse=True)

print(f"{'PID':<10} {'PROCESS':<30} {'MEMORY GB':>10}")
print("-" * 55)

for pid, name, memory in processes[:15]:
    print(f"{pid:<10} {name:<30} {memory:>10.2f}")

PID        PROCESS                         MEMORY GB
-------------------------------------------------------
23324      vmware-vmx.exe                       2.62
3980       MemCompression                       2.29
19816      brave.exe                            0.85
27296      brave.exe                            0.61
15012      brave.exe                            0.52
32968      brave.exe                            0.51
23828      Code.exe                             0.49
36936      ChatGPT.exe                          0.47
9564       dwm.exe                              0.46
25228      Code.exe                             0.46
5380       MsMpEng.exe                          0.45
17608      ONENOTE.EXE                          0.43
5328       MsSense.exe                          0.41
24480      Code.exe                             0.41
31956      msedgewebview2.exe                   0.39


Yes. Your Task Manager currently shows roughly **31.5 GB used out of 64 GB (49%)**, with about **32.4 GB available**. That is healthy; you still have plenty of available RAM.

You can check the same information using both PowerShell and Python.

## PowerShell

### 1. Simple memory check

```powershell
Get-CimInstance Win32_OperatingSystem | Select-Object `
@{Name="TotalMemoryGB";Expression={[math]::Round($_.TotalVisibleMemorySize/1MB,2)}},
@{Name="FreeMemoryGB";Expression={[math]::Round($_.FreePhysicalMemory/1MB,2)}}
```

You should see something similar to:

```text
TotalMemoryGB FreeMemoryGB
------------- ------------
64.00         32.40
```

### 2. Show used, free, and percentage

This is more useful:

```powershell
$os = Get-CimInstance Win32_OperatingSystem

$total = $os.TotalVisibleMemorySize
$free = $os.FreePhysicalMemory
$used = $total - $free

Write-Host "Total Memory :" ([math]::Round($total/1MB,2)) "GB"
Write-Host "Used Memory  :" ([math]::Round($used/1MB,2)) "GB"
Write-Host "Free Memory  :" ([math]::Round($free/1MB,2)) "GB"
Write-Host "Memory Usage :" ([math]::Round(($used/$total)*100,2)) "%"
```

### 3. Find processes using the most RAM

This is excellent for troubleshooting:

```powershell
Get-Process |
Sort-Object WorkingSet64 -Descending |
Select-Object -First 10 Name, Id,
@{Name="MemoryGB";Expression={[math]::Round($_.WorkingSet64/1GB,2)}}
```

For example:

```text
Name          Id      MemoryGB
----          --      --------
vmware-vmx    12452     12.50
chrome        18232      2.10
Code          15432      1.20
...
```

This would be especially useful if you want to determine whether a VMware VM is responsible for your ~31 GB usage.

---

# Python

Install `psutil` once:

```powershell
pip install psutil
```

### 1. Simple memory check

```python
import psutil

memory = psutil.virtual_memory()

print(f"Total     : {memory.total / (1024**3):.2f} GB")
print(f"Used      : {memory.used / (1024**3):.2f} GB")
print(f"Available : {memory.available / (1024**3):.2f} GB")
print(f"Usage     : {memory.percent}%")
```

You'll get something like:

```text
Total     : 64.00 GB
Used      : 31.50 GB
Available : 32.40 GB
Usage     : 49.2%
```

### 2. CPU + memory together

I'd recommend this for general monitoring:

```python
import psutil
import time

while True:

    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()

    print("\n===== SYSTEM STATUS =====")

    print(f"CPU Usage       : {cpu}%")
    print(f"Memory Usage    : {memory.percent}%")
    print(f"Memory Used     : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Available: {memory.available / (1024**3):.2f} GB")
    print(f"Memory Total    : {memory.total / (1024**3):.2f} GB")

    time.sleep(2)
```

### 3. Find which processes are using the most RAM

```python
import psutil

processes = []

for process in psutil.process_iter(
    ['pid', 'name', 'memory_info']
):
    try:
        memory_gb = process.info['memory_info'].rss / (1024**3)

        processes.append(
            (
                process.info['pid'],
                process.info['name'],
                memory_gb
            )
        )

    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass


processes.sort(key=lambda x: x[2], reverse=True)

print(f"{'PID':<10} {'PROCESS':<30} {'MEMORY GB':>10}")
print("-" * 55)

for pid, name, memory in processes[:15]:
    print(f"{pid:<10} {name:<30} {memory:>10.2f}")
```

That will give you something like:

```text
PID        PROCESS                         MEMORY GB
-------------------------------------------------------
12540      vmware-vmx.exe                     12.34
18324      chrome.exe                          2.31
15120      Code.exe                            1.42
...
```

For your machine, this **process-level check is the next one I'd run**, because it will explain where that **~31.5 GB of RAM** is going rather than only telling you that 49% is being used.

In [11]:
import psutil

disk = psutil.disk_usage("C:\\")

print(f"Total : {disk.total / (1024**3):.2f} GB")
print(f"Used  : {disk.used / (1024**3):.2f} GB")
print(f"Free  : {disk.free / (1024**3):.2f} GB")
print(f"Usage : {disk.percent}%")

Total : 2047.45 GB
Used  : 309.49 GB
Free  : 1737.96 GB
Usage : 15.1%


In [12]:
import psutil
import time

before = psutil.disk_io_counters()

time.sleep(1)

after = psutil.disk_io_counters()

read_speed = after.read_bytes - before.read_bytes
write_speed = after.write_bytes - before.write_bytes

print(f"Read  : {read_speed / 1024:.2f} KB/s")
print(f"Write : {write_speed / 1024:.2f} KB/s")

Read  : 16134.50 KB/s
Write : 5852.00 KB/s


In [13]:
import psutil
import time

while True:

    before = psutil.disk_io_counters()
    time.sleep(1)
    after = psutil.disk_io_counters()

    read_speed = after.read_bytes - before.read_bytes
    write_speed = after.write_bytes - before.write_bytes

    disk = psutil.disk_usage("C:\\")

    print("\n===== DISK STATUS =====")
    print(f"Disk Usage : {disk.percent}%")
    print(f"Free Space : {disk.free / (1024**3):.2f} GB")
    print(f"Read Speed : {read_speed / (1024**2):.2f} MB/s")
    print(f"Write Speed: {write_speed / (1024**2):.2f} MB/s")


===== DISK STATUS =====
Disk Usage : 15.1%
Free Space : 1737.82 GB
Read Speed : 15.51 MB/s
Write Speed: 7.80 MB/s

===== DISK STATUS =====
Disk Usage : 15.1%
Free Space : 1737.82 GB
Read Speed : 17.02 MB/s
Write Speed: 3.97 MB/s

===== DISK STATUS =====
Disk Usage : 15.1%
Free Space : 1737.82 GB
Read Speed : 15.28 MB/s
Write Speed: 7.11 MB/s

===== DISK STATUS =====
Disk Usage : 15.1%
Free Space : 1737.82 GB
Read Speed : 15.48 MB/s
Write Speed: 4.55 MB/s

===== DISK STATUS =====
Disk Usage : 15.1%
Free Space : 1737.80 GB
Read Speed : 16.72 MB/s
Write Speed: 1.10 MB/s


KeyboardInterrupt: 

In [14]:
import psutil
import time

while True:

    # CPU
    cpu = psutil.cpu_percent(interval=1)

    # Memory
    memory = psutil.virtual_memory()

    # Disk capacity
    disk = psutil.disk_usage("C:\\")

    # Disk I/O
    before = psutil.disk_io_counters()
    time.sleep(1)
    after = psutil.disk_io_counters()

    read_mb = (after.read_bytes - before.read_bytes) / (1024**2)
    write_mb = (after.write_bytes - before.write_bytes) / (1024**2)

    print("\n========== SYSTEM MONITOR ==========")

    print(f"CPU Usage       : {cpu:.1f}%")

    print("\n--- MEMORY ---")
    print(f"Memory Usage    : {memory.percent:.1f}%")
    print(f"Memory Used     : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Available: {memory.available / (1024**3):.2f} GB")

    print("\n--- DISK ---")
    print(f"Disk Usage      : {disk.percent:.1f}%")
    print(f"Disk Used       : {disk.used / (1024**3):.2f} GB")
    print(f"Disk Free       : {disk.free / (1024**3):.2f} GB")
    print(f"Disk Read       : {read_mb:.2f} MB/s")
    print(f"Disk Write      : {write_mb:.2f} MB/s")

    print("====================================")


========== SYSTEM MONITOR ==========
CPU Usage       : 64.0%

--- MEMORY ---
Memory Usage    : 44.2%
Memory Used     : 28.28 GB
Memory Available: 35.67 GB

--- DISK ---
Disk Usage      : 15.1%
Disk Used       : 309.69 GB
Disk Free       : 1737.75 GB
Disk Read       : 16.51 MB/s
Disk Write      : 5.55 MB/s

========== SYSTEM MONITOR ==========
CPU Usage       : 31.4%

--- MEMORY ---
Memory Usage    : 44.2%
Memory Used     : 28.30 GB
Memory Available: 35.65 GB

--- DISK ---
Disk Usage      : 15.1%
Disk Used       : 309.71 GB
Disk Free       : 1737.74 GB
Disk Read       : 16.69 MB/s
Disk Write      : 7.36 MB/s

========== SYSTEM MONITOR ==========
CPU Usage       : 46.6%

--- MEMORY ---
Memory Usage    : 44.2%
Memory Used     : 28.29 GB
Memory Available: 35.66 GB

--- DISK ---
Disk Usage      : 15.1%
Disk Used       : 309.73 GB
Disk Free       : 1737.72 GB
Disk Read       : 17.26 MB/s
Disk Write      : 8.16 MB/s

========== SYSTEM MONITOR ==========
CPU Usage       : 40.4%

--- MEMORY --

KeyboardInterrupt: 

Yes. You can check **disk utilization, capacity, free space, read/write activity, and disk performance** using both Python and PowerShell.

From your screenshot, Disk 0 is a **2 TB HDD (SAS)** and is currently only around **2% active**, so it is not heavily utilized at that moment.

## PowerShell

### 1. Check disk capacity and free space

```powershell
Get-PSDrive C
```

For a cleaner GB view:

```powershell
Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'" |
Select-Object DeviceID,
@{Name="TotalGB";Expression={[math]::Round($_.Size/1GB,2)}},
@{Name="FreeGB";Expression={[math]::Round($_.FreeSpace/1GB,2)}},
@{Name="UsedGB";Expression={[math]::Round(($_.Size-$_.FreeSpace)/1GB,2)}},
@{Name="FreePercent";Expression={[math]::Round(($_.FreeSpace/$_.Size)*100,2)}}
```

### 2. Check live disk utilization

This is similar to the **Active time %** in Task Manager:

```powershell
Get-Counter '\PhysicalDisk(_Total)\% Disk Time'
```

Continuous monitoring every 2 seconds:

```powershell
Get-Counter '\PhysicalDisk(_Total)\% Disk Time' `
-SampleInterval 2 -Continuous
```

### 3. Check disk read/write speed

```powershell
Get-Counter '\PhysicalDisk(_Total)\Disk Read Bytes/sec',
            '\PhysicalDisk(_Total)\Disk Write Bytes/sec'
```

### 4. Check disk latency

```powershell
Get-Counter '\PhysicalDisk(_Total)\Avg. Disk sec/Read',
            '\PhysicalDisk(_Total)\Avg. Disk sec/Write'
```

These are useful when troubleshooting a slow server.

---

# Python

Install `psutil` if you haven't already:

```powershell
pip install psutil
```

### 1. Check disk capacity

```python
import psutil

disk = psutil.disk_usage("C:\\")

print(f"Total : {disk.total / (1024**3):.2f} GB")
print(f"Used  : {disk.used / (1024**3):.2f} GB")
print(f"Free  : {disk.free / (1024**3):.2f} GB")
print(f"Usage : {disk.percent}%")
```

Example:

```text
Total : 2048.00 GB
Used  : 850.25 GB
Free  : 1197.75 GB
Usage : 41.5%
```

Notice that this **usage percentage means storage capacity used**, not Task Manager's **Active time**.

### 2. Check disk read/write activity

```python
import psutil
import time

before = psutil.disk_io_counters()

time.sleep(1)

after = psutil.disk_io_counters()

read_speed = after.read_bytes - before.read_bytes
write_speed = after.write_bytes - before.write_bytes

print(f"Read  : {read_speed / 1024:.2f} KB/s")
print(f"Write : {write_speed / 1024:.2f} KB/s")
```

This is closer to the Task Manager values such as:

```text
Read speed  : 129 KB/s
Write speed : 487 KB/s
```

### 3. Continuous disk monitoring

```python
import psutil
import time

while True:

    before = psutil.disk_io_counters()
    time.sleep(1)
    after = psutil.disk_io_counters()

    read_speed = after.read_bytes - before.read_bytes
    write_speed = after.write_bytes - before.write_bytes

    disk = psutil.disk_usage("C:\\")

    print("\n===== DISK STATUS =====")
    print(f"Disk Usage : {disk.percent}%")
    print(f"Free Space : {disk.free / (1024**3):.2f} GB")
    print(f"Read Speed : {read_speed / (1024**2):.2f} MB/s")
    print(f"Write Speed: {write_speed / (1024**2):.2f} MB/s")
```

## One Python script for CPU + RAM + Disk

Since you're checking all three resources, you can combine them:

```python
import psutil
import time

while True:

    # CPU
    cpu = psutil.cpu_percent(interval=1)

    # Memory
    memory = psutil.virtual_memory()

    # Disk capacity
    disk = psutil.disk_usage("C:\\")

    # Disk I/O
    before = psutil.disk_io_counters()
    time.sleep(1)
    after = psutil.disk_io_counters()

    read_mb = (after.read_bytes - before.read_bytes) / (1024**2)
    write_mb = (after.write_bytes - before.write_bytes) / (1024**2)

    print("\n========== SYSTEM MONITOR ==========")

    print(f"CPU Usage       : {cpu:.1f}%")

    print("\n--- MEMORY ---")
    print(f"Memory Usage    : {memory.percent:.1f}%")
    print(f"Memory Used     : {memory.used / (1024**3):.2f} GB")
    print(f"Memory Available: {memory.available / (1024**3):.2f} GB")

    print("\n--- DISK ---")
    print(f"Disk Usage      : {disk.percent:.1f}%")
    print(f"Disk Used       : {disk.used / (1024**3):.2f} GB")
    print(f"Disk Free       : {disk.free / (1024**3):.2f} GB")
    print(f"Disk Read       : {read_mb:.2f} MB/s")
    print(f"Disk Write      : {write_mb:.2f} MB/s")

    print("====================================")
```

This gives you a simple Python-based **Task Manager-style monitor** for CPU, memory, and disk.

In [15]:
import psutil

net = psutil.net_io_counters()

print(f"Bytes Sent     : {net.bytes_sent}")
print(f"Bytes Received : {net.bytes_recv}")
print(f"Packets Sent   : {net.packets_sent}")
print(f"Packets Recv   : {net.packets_recv}")
print(f"Errors In      : {net.errin}")
print(f"Errors Out     : {net.errout}")

Bytes Sent     : 7050645730
Bytes Received : 5844475139
Packets Sent   : 4973253
Packets Recv   : 5245409
Errors In      : 0
Errors Out     : 0


In [16]:
import psutil
import time

while True:
    before = psutil.net_io_counters()

    time.sleep(1)

    after = psutil.net_io_counters()

    sent_bytes = after.bytes_sent - before.bytes_sent
    recv_bytes = after.bytes_recv - before.bytes_recv

    sent_mbps = (sent_bytes * 8) / 1_000_000
    recv_mbps = (recv_bytes * 8) / 1_000_000

    print(f"Send    : {sent_mbps:.2f} Mbps")
    print(f"Receive : {recv_mbps:.2f} Mbps")
    print("-----------------------------")

Send    : 17.10 Mbps
Receive : 0.20 Mbps
-----------------------------
Send    : 12.71 Mbps
Receive : 0.24 Mbps
-----------------------------
Send    : 11.65 Mbps
Receive : 0.10 Mbps
-----------------------------
Send    : 13.45 Mbps
Receive : 0.25 Mbps
-----------------------------
Send    : 18.35 Mbps
Receive : 0.28 Mbps
-----------------------------


KeyboardInterrupt: 

In [17]:
import psutil
import time

interface = "Ethernet 2"

while True:
    before = psutil.net_io_counters(pernic=True)[interface]

    time.sleep(1)

    after = psutil.net_io_counters(pernic=True)[interface]

    sent_mbps = ((after.bytes_sent - before.bytes_sent) * 8) / 1_000_000
    recv_mbps = ((after.bytes_recv - before.bytes_recv) * 8) / 1_000_000

    print(f"\nInterface : {interface}")
    print(f"Send      : {sent_mbps:.2f} Mbps")
    print(f"Receive   : {recv_mbps:.2f} Mbps")


Interface : Ethernet 2
Send      : 16.80 Mbps
Receive   : 0.16 Mbps

Interface : Ethernet 2
Send      : 15.49 Mbps
Receive   : 0.12 Mbps

Interface : Ethernet 2
Send      : 18.04 Mbps
Receive   : 0.16 Mbps

Interface : Ethernet 2
Send      : 17.03 Mbps
Receive   : 0.21 Mbps

Interface : Ethernet 2
Send      : 14.29 Mbps
Receive   : 0.09 Mbps

Interface : Ethernet 2
Send      : 15.14 Mbps
Receive   : 0.08 Mbps


KeyboardInterrupt: 

In [18]:
import psutil

for interface in psutil.net_if_addrs():
    print(interface)

Ethernet 2
VMware Network Adapter VMnet1
VMware Network Adapter VMnet8
vEthernet (Default Switch)
Loopback Pseudo-Interface 1


Yes. From your screenshot, Task Manager is showing Ethernet traffic on **Ethernet 2**, with roughly:

- **Send:** 9.3 Mbps
- **Receive:** 488 Kbps
- IPv4 address: `10.0.9.200`

You can check similar information with both PowerShell and Python.

### PowerShell

Check all network adapters:

```powershell
Get-NetAdapter
```

Check IP information:

```powershell
Get-NetIPConfiguration
```

Check Ethernet 2 specifically:

```powershell
Get-NetAdapter -Name "Ethernet 2"
```

Check interface statistics:

```powershell
Get-NetAdapterStatistics -Name "Ethernet 2"
```

This gives transmitted and received bytes, packets, errors, and discards.

For live throughput using performance counters:

```powershell
Get-Counter '\Network Interface(*)\Bytes Total/sec'
```

For send and receive separately:

```powershell
Get-Counter `
'\Network Interface(*)\Bytes Sent/sec',
'\Network Interface(*)\Bytes Received/sec'
```

Continuous monitoring every 2 seconds:

```powershell
Get-Counter `
'\Network Interface(*)\Bytes Sent/sec',
'\Network Interface(*)\Bytes Received/sec' `
-SampleInterval 2 -Continuous
```

To convert bytes/sec into Mbps:

```powershell
Get-Counter '\Network Interface(*)\Bytes Total/sec' |
Select-Object -ExpandProperty CounterSamples |
Select-Object InstanceName,
@{Name="Mbps";Expression={[math]::Round(($_.CookedValue * 8) / 1MB,2)}}
```

### Python

Install `psutil` if needed:

```powershell
pip install psutil
```

Simple total network counters:

```python
import psutil

net = psutil.net_io_counters()

print(f"Bytes Sent     : {net.bytes_sent}")
print(f"Bytes Received : {net.bytes_recv}")
print(f"Packets Sent   : {net.packets_sent}")
print(f"Packets Recv   : {net.packets_recv}")
print(f"Errors In      : {net.errin}")
print(f"Errors Out     : {net.errout}")
```

For live send/receive speeds:

```python
import psutil
import time

while True:
    before = psutil.net_io_counters()

    time.sleep(1)

    after = psutil.net_io_counters()

    sent_bytes = after.bytes_sent - before.bytes_sent
    recv_bytes = after.bytes_recv - before.bytes_recv

    sent_mbps = (sent_bytes * 8) / 1_000_000
    recv_mbps = (recv_bytes * 8) / 1_000_000

    print(f"Send    : {sent_mbps:.2f} Mbps")
    print(f"Receive : {recv_mbps:.2f} Mbps")
    print("-----------------------------")
```

You may see output like:

```text
Send    : 9.25 Mbps
Receive : 0.49 Mbps
-----------------------------
Send    : 7.82 Mbps
Receive : 0.61 Mbps
```

That is the closest equivalent to the **Send/Receive** numbers you see in Task Manager.

For a specific adapter such as `Ethernet 2`:

```python
import psutil
import time

interface = "Ethernet 2"

while True:
    before = psutil.net_io_counters(pernic=True)[interface]

    time.sleep(1)

    after = psutil.net_io_counters(pernic=True)[interface]

    sent_mbps = ((after.bytes_sent - before.bytes_sent) * 8) / 1_000_000
    recv_mbps = ((after.bytes_recv - before.bytes_recv) * 8) / 1_000_000

    print(f"\nInterface : {interface}")
    print(f"Send      : {sent_mbps:.2f} Mbps")
    print(f"Receive   : {recv_mbps:.2f} Mbps")
```

And to list all interface names first:

```python
import psutil

for interface in psutil.net_if_addrs():
    print(interface)
```

You should see entries such as:

```text
Ethernet 2
VMware Network Adapter VMnet1
VMware Network Adapter VMnet8
```

For your Windows system, I would use `psutil.net_io_counters(pernic=True)` because it lets you separate the physical/Hyper-V Ethernet interface from the VMware virtual adapters.

In [19]:
import psutil
import time
import os

INTERVAL = 2

def gb(value):
    return value / (1024 ** 3)

def mb(value):
    return value / (1024 ** 2)

# Prime CPU counters
for p in psutil.process_iter():
    try:
        p.cpu_percent(None)
    except:
        pass

# Initial disk I/O counters
old_io = {}

for p in psutil.process_iter(['pid']):
    try:
        io = p.io_counters()
        old_io[p.pid] = io.read_bytes + io.write_bytes
    except:
        pass

# Initial network counters
old_net = psutil.net_io_counters()

while True:

    time.sleep(INTERVAL)

    os.system("cls" if os.name == "nt" else "clear")

    # ------------------------------------------------
    # SYSTEM SUMMARY
    # ------------------------------------------------

    cpu_total = psutil.cpu_percent(None)

    memory = psutil.virtual_memory()

    disk = psutil.disk_usage("C:\\")

    new_net = psutil.net_io_counters()

    sent_mbps = (
        (new_net.bytes_sent - old_net.bytes_sent) * 8
        / INTERVAL
        / 1_000_000
    )

    recv_mbps = (
        (new_net.bytes_recv - old_net.bytes_recv) * 8
        / INTERVAL
        / 1_000_000
    )

    old_net = new_net

    print("=" * 90)
    print("                    WINDOWS SYSTEM MONITOR")
    print("=" * 90)

    print(
        f"CPU: {cpu_total:5.1f}%   "
        f"Memory: {memory.percent:5.1f}%   "
        f"Disk C: {disk.percent:5.1f}%   "
        f"Network TX: {sent_mbps:7.2f} Mbps   "
        f"RX: {recv_mbps:7.2f} Mbps"
    )

    print("=" * 90)

    # ------------------------------------------------
    # PROCESS INFORMATION
    # ------------------------------------------------

    processes = []

    for p in psutil.process_iter(
        ['pid', 'name', 'memory_info']
    ):

        try:

            cpu = p.cpu_percent(None)

            memory_mb = (
                p.info['memory_info'].rss / (1024 ** 2)
            )

            try:
                io = p.io_counters()

                current_io = (
                    io.read_bytes +
                    io.write_bytes
                )

                previous_io = old_io.get(
                    p.pid,
                    current_io
                )

                disk_rate = (
                    current_io -
                    previous_io
                ) / INTERVAL / (1024 ** 2)

                old_io[p.pid] = current_io

            except:
                disk_rate = 0

            processes.append(
                {
                    "pid": p.pid,
                    "name": p.info['name'],
                    "cpu": cpu,
                    "memory": memory_mb,
                    "disk": disk_rate
                }
            )

        except (
            psutil.NoSuchProcess,
            psutil.AccessDenied
        ):
            continue

    # Sort by CPU usage
    processes.sort(
        key=lambda x: x["cpu"],
        reverse=True
    )

    print(
        f"{'PID':<8}"
        f"{'PROCESS':<35}"
        f"{'CPU %':>10}"
        f"{'MEMORY MB':>15}"
        f"{'DISK MB/s':>15}"
    )

    print("-" * 90)

    for p in processes[:20]:

        print(
            f"{p['pid']:<8}"
            f"{p['name'][:32]:<35}"
            f"{p['cpu']:>10.1f}"
            f"{p['memory']:>15.1f}"
            f"{p['disk']:>15.2f}"
        )

                    WINDOWS SYSTEM MONITOR
CPU:  37.7%   Memory:  44.1%   Disk C:  15.1%   Network TX:   14.67 Mbps   RX:    0.14 Mbps
PID     PROCESS                                 CPU %      MEMORY MB      DISK MB/s
------------------------------------------------------------------------------------------
0       System Idle Process                     916.4            0.0           0.00
2920    svchost.exe                             112.0          294.9           0.04
41588   python3.13.exe                           80.6           99.1           0.00
28368   BackgroundDownload.exe                   33.7          175.3         452.92
5380    MsMpEng.exe                              28.7          446.1           0.00
9412    Code.exe                                 28.5          144.8          20.55
4       System                                   25.6            0.2           0.08
5328    MsSense.exe                              23.9          419.9           0.01
8736    WmiPrvSE.e

KeyboardInterrupt: 

Yes. You can reproduce most of the **Task Manager → Processes** view with Python and PowerShell.

From your screenshot, Task Manager is showing per-process **CPU, Memory, Disk, and Network** usage. Python can easily show CPU, memory, and disk I/O per process. Per-process network bandwidth is harder because Windows does not expose it cleanly through `psutil`, but we can still show overall network throughput.

First install `psutil`:

```powershell
pip install psutil
```

Use this Python script:

```python
import psutil
import time
import os

INTERVAL = 2

def gb(value):
    return value / (1024 ** 3)

def mb(value):
    return value / (1024 ** 2)

# Prime CPU counters
for p in psutil.process_iter():
    try:
        p.cpu_percent(None)
    except:
        pass

# Initial disk I/O counters
old_io = {}

for p in psutil.process_iter(['pid']):
    try:
        io = p.io_counters()
        old_io[p.pid] = io.read_bytes + io.write_bytes
    except:
        pass

# Initial network counters
old_net = psutil.net_io_counters()

while True:

    time.sleep(INTERVAL)

    os.system("cls" if os.name == "nt" else "clear")

    # ------------------------------------------------
    # SYSTEM SUMMARY
    # ------------------------------------------------

    cpu_total = psutil.cpu_percent(None)

    memory = psutil.virtual_memory()

    disk = psutil.disk_usage("C:\\")

    new_net = psutil.net_io_counters()

    sent_mbps = (
        (new_net.bytes_sent - old_net.bytes_sent) * 8
        / INTERVAL
        / 1_000_000
    )

    recv_mbps = (
        (new_net.bytes_recv - old_net.bytes_recv) * 8
        / INTERVAL
        / 1_000_000
    )

    old_net = new_net

    print("=" * 90)
    print("                    WINDOWS SYSTEM MONITOR")
    print("=" * 90)

    print(
        f"CPU: {cpu_total:5.1f}%   "
        f"Memory: {memory.percent:5.1f}%   "
        f"Disk C: {disk.percent:5.1f}%   "
        f"Network TX: {sent_mbps:7.2f} Mbps   "
        f"RX: {recv_mbps:7.2f} Mbps"
    )

    print("=" * 90)

    # ------------------------------------------------
    # PROCESS INFORMATION
    # ------------------------------------------------

    processes = []

    for p in psutil.process_iter(
        ['pid', 'name', 'memory_info']
    ):

        try:

            cpu = p.cpu_percent(None)

            memory_mb = (
                p.info['memory_info'].rss / (1024 ** 2)
            )

            try:
                io = p.io_counters()

                current_io = (
                    io.read_bytes +
                    io.write_bytes
                )

                previous_io = old_io.get(
                    p.pid,
                    current_io
                )

                disk_rate = (
                    current_io -
                    previous_io
                ) / INTERVAL / (1024 ** 2)

                old_io[p.pid] = current_io

            except:
                disk_rate = 0

            processes.append(
                {
                    "pid": p.pid,
                    "name": p.info['name'],
                    "cpu": cpu,
                    "memory": memory_mb,
                    "disk": disk_rate
                }
            )

        except (
            psutil.NoSuchProcess,
            psutil.AccessDenied
        ):
            continue

    # Sort by CPU usage
    processes.sort(
        key=lambda x: x["cpu"],
        reverse=True
    )

    print(
        f"{'PID':<8}"
        f"{'PROCESS':<35}"
        f"{'CPU %':>10}"
        f"{'MEMORY MB':>15}"
        f"{'DISK MB/s':>15}"
    )

    print("-" * 90)

    for p in processes[:20]:

        print(
            f"{p['pid']:<8}"
            f"{p['name'][:32]:<35}"
            f"{p['cpu']:>10.1f}"
            f"{p['memory']:>15.1f}"
            f"{p['disk']:>15.2f}"
        )
```

You will get a terminal display similar to:

```text
==========================================================================================
                    WINDOWS SYSTEM MONITOR
==========================================================================================
CPU: 29.4%   Memory: 49.2%   Disk C: 41.3%   Network TX: 9.21 Mbps   RX: 0.48 Mbps
==========================================================================================

PID     PROCESS                              CPU %      MEMORY MB      DISK MB/s
------------------------------------------------------------------------------------------
10428   brave.exe                             6.8         865.4            0.12
15320   Taskmgr.exe                           3.4         118.5            0.00
11244   ChatGPT.exe                           1.7         522.3            0.04
18204   chrome.exe                            0.8         412.7            0.03
14320   Code.exe                              0.4         693.2            0.01
...
```

This refreshes every **2 seconds**, similar to Task Manager.

One important difference: browsers such as Brave and Chrome create many subprocesses. Task Manager groups them as something like `Brave Browser (40)`, while this Python script shows individual `brave.exe` processes unless you add grouping logic.

For the **terminal / PowerShell** side, these are the most useful commands:

- Overall CPU:

```powershell
Get-CimInstance Win32_Processor |
Select-Object LoadPercentage
```

- Top processes by CPU:

```powershell
Get-Process |
Sort-Object CPU -Descending |
Select-Object -First 15 Name, Id, CPU
```

- Top processes by RAM:

```powershell
Get-Process |
Sort-Object WorkingSet64 -Descending |
Select-Object -First 15 Name, Id,
@{Name="MemoryMB";Expression={[math]::Round($_.WorkingSet64/1MB,2)}}
```

- Disk activity:

```powershell
Get-Counter `
'\PhysicalDisk(_Total)\% Disk Time',
'\PhysicalDisk(_Total)\Disk Read Bytes/sec',
'\PhysicalDisk(_Total)\Disk Write Bytes/sec'
```

- Network throughput:

```powershell
Get-Counter `
'\Network Interface(*)\Bytes Sent/sec',
'\Network Interface(*)\Bytes Received/sec'
```

- CPU, memory, disk, and network counters together:

```powershell
Get-Counter `
'\Processor(_Total)\% Processor Time',
'\Memory\% Committed Bytes In Use',
'\PhysicalDisk(_Total)\% Disk Time',
'\Network Interface(*)\Bytes Sent/sec',
'\Network Interface(*)\Bytes Received/sec' `
-SampleInterval 2 `
-Continuous
```

For your use case, the Python script above is the better option because it gives you a **single terminal dashboard similar to Task Manager** and can later be extended to save CPU/RAM/disk/network spikes into a log file.

In [20]:
import psutil
from datetime import datetime

boot = datetime.fromtimestamp(psutil.boot_time())
print("Boot Time:", boot)
print("Uptime:", datetime.now() - boot)

Boot Time: 2026-08-29 19:45:12.542718
Uptime: 5:19:56.434035


In [21]:
import psutil

for p in psutil.process_iter(["pid", "name", "status"]):
    print(p.info)

{'pid': 0, 'name': 'System Idle Process', 'status': 'running'}
{'pid': 4, 'name': 'System', 'status': 'running'}
{'pid': 236, 'name': '', 'status': 'stopped'}
{'pid': 276, 'name': 'Registry', 'status': 'running'}
{'pid': 400, 'name': 'CrossDeviceResume.exe', 'status': 'running'}
{'pid': 464, 'name': 'ChatGPT.exe', 'status': 'running'}
{'pid': 1112, 'name': 'EpmService.exe', 'status': 'running'}
{'pid': 1224, 'name': 'smss.exe', 'status': 'running'}
{'pid': 1352, 'name': 'LogonUI.exe', 'status': 'running'}
{'pid': 1396, 'name': 'csrss.exe', 'status': 'running'}
{'pid': 1464, 'name': 'dwm.exe', 'status': 'running'}
{'pid': 1468, 'name': 'csrss.exe', 'status': 'running'}
{'pid': 1480, 'name': 'svchost.exe', 'status': 'running'}
{'pid': 1492, 'name': 'wininit.exe', 'status': 'running'}
{'pid': 1528, 'name': 'winlogon.exe', 'status': 'running'}
{'pid': 1612, 'name': 'services.exe', 'status': 'running'}
{'pid': 1656, 'name': 'LsaIso.exe', 'status': 'running'}
{'pid': 1664, 'name': 'lsass.exe

In [22]:
import psutil

for conn in psutil.net_connections(kind="inet"):
    if conn.status == "LISTEN":
        print(
            "Local:", conn.laddr,
            "PID:", conn.pid
        )

Local: addr(ip='::', port=135) PID: 1848
Local: addr(ip='0.0.0.0', port=55548) PID: 18496
Local: addr(ip='::', port=49666) PID: 2556
Local: addr(ip='127.0.0.1', port=51388) PID: 24592
Local: addr(ip='::1', port=42050) PID: 26340
Local: addr(ip='127.0.0.1', port=62343) PID: 16160
Local: addr(ip='::', port=49665) PID: 1492
Local: addr(ip='0.0.0.0', port=5040) PID: 12804
Local: addr(ip='::', port=49681) PID: 3616
Local: addr(ip='0.0.0.0', port=2179) PID: 3136
Local: addr(ip='::', port=2179) PID: 3136
Local: addr(ip='0.0.0.0', port=7680) PID: 4236
Local: addr(ip='::', port=49694) PID: 4944
Local: addr(ip='192.168.32.1', port=139) PID: 4
Local: addr(ip='::', port=49667) PID: 4676
Local: addr(ip='127.0.0.1', port=49737) PID: 25228
Local: addr(ip='10.0.9.200', port=139) PID: 4
Local: addr(ip='::', port=49664) PID: 1664
Local: addr(ip='0.0.0.0', port=49664) PID: 1664
Local: addr(ip='::', port=49693) PID: 1612
Local: addr(ip='127.0.0.1', port=55949) PID: 41588
Local: addr(ip='172.20.96.1', port

In [23]:
import psutil

PORT = 443

for conn in psutil.net_connections(kind="inet"):
    if conn.laddr and conn.laddr.port == PORT:
        print("PID:", conn.pid)

        if conn.pid:
            try:
                print("Process:", psutil.Process(conn.pid).name())
            except psutil.Error:
                pass

In [24]:
import psutil

for interface, addresses in psutil.net_if_addrs().items():
    print(f"\n{interface}")

    for addr in addresses:
        print(" ", addr.address)


Ethernet 2
  00-0D-3A-FD-68-B8
  10.0.9.200
  fe80::6132:4038:d2f8:271e

VMware Network Adapter VMnet1
  00-50-56-C0-00-01
  192.168.229.1
  fe80::528:7233:f4e5:b512

VMware Network Adapter VMnet8
  00-50-56-C0-00-08
  192.168.32.1
  fe80::1fdc:299:134a:52b2

vEthernet (Default Switch)
  00-15-5D-71-52-BC
  172.20.96.1
  fe80::3b95:d0ca:e26b:2dde

Loopback Pseudo-Interface 1
  127.0.0.1
  ::1


In [25]:
import psutil

stats = psutil.net_if_stats()

for name, data in stats.items():
    print(
        name,
        "UP:" if data.isup else "DOWN:",
        data.speed,
        "Mbps"
    )

vEthernet (Default Switch) UP: 4294 Mbps
Ethernet 2 UP: 4294 Mbps
VMware Network Adapter VMnet1 UP: 100 Mbps
VMware Network Adapter VMnet8 UP: 100 Mbps
Loopback Pseudo-Interface 1 UP: 1073 Mbps


In [26]:
import subprocess

hosts = [
    "8.8.8.8",
    "1.1.1.1",
    "192.168.32.128"
]

for host in hosts:

    result = subprocess.run(
        ["ping", "-n", "1", host],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print(host, "UP")
    else:
        print(host, "DOWN")

8.8.8.8 DOWN
1.1.1.1 DOWN
192.168.32.128 UP


In [27]:
import socket

host = "8.8.8.8"
port = 443

try:
    connection = socket.create_connection(
        (host, port),
        timeout=3
    )

    print(f"{host}:{port} reachable")
    connection.close()

except Exception as error:
    print(f"{host}:{port} failed")
    print(error)

8.8.8.8:443 reachable


In [28]:
import socket

hostname = "google.com"

try:
    ip = socket.gethostbyname(hostname)

    print("Hostname :", hostname)
    print("IP       :", ip)

except socket.gaierror:
    print("DNS resolution failed")

Hostname : google.com
IP       : 142.251.33.206


In [29]:
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status == "ESTABLISHED":

        print(
            conn.laddr,
            " --> ",
            conn.raddr,
            "PID:",
            conn.pid
        )

addr(ip='127.0.0.1', port=56542)  -->  addr(ip='127.0.0.1', port=56543) PID: 11988
addr(ip='10.0.9.200', port=65027)  -->  addr(ip='104.40.82.182', port=443) PID: 33024
addr(ip='127.0.0.1', port=56565)  -->  addr(ip='127.0.0.1', port=56564) PID: 11988
addr(ip='127.0.0.1', port=9010)  -->  addr(ip='127.0.0.1', port=55965) PID: 41588
addr(ip='127.0.0.1', port=56545)  -->  addr(ip='127.0.0.1', port=56544) PID: 11988
addr(ip='127.0.0.1', port=56533)  -->  addr(ip='127.0.0.1', port=56532) PID: 11988
addr(ip='10.0.9.200', port=59216)  -->  addr(ip='20.29.134.17', port=443) PID: 25228
addr(ip='10.0.9.200', port=51351)  -->  addr(ip='52.108.8.12', port=443) PID: 33084
addr(ip='127.0.0.1', port=56554)  -->  addr(ip='127.0.0.1', port=56556) PID: 11988
addr(ip='10.0.9.200', port=50496)  -->  addr(ip='3.254.239.146', port=443) PID: 30468
addr(ip='127.0.0.1', port=55953)  -->  addr(ip='127.0.0.1', port=55952) PID: 41588
addr(ip='127.0.0.1', port=55945)  -->  addr(ip='127.0.0.1', port=55946) PID: 41

In [30]:
import psutil

battery = psutil.sensors_battery()

if battery:
    print("Battery:", battery.percent, "%")
    print("Charging:", battery.power_plugged)
else:
    print("No battery detected")

No battery detected


In [31]:
import psutil

target = "chrome.exe"

for p in psutil.process_iter(
    ["pid", "name", "memory_info"]
):
    try:
        if p.info["name"].lower() == target:

            print(
                "PID:",
                p.info["pid"],
                "RAM:",
                round(
                    p.info["memory_info"].rss / 1024**2,
                    2
                ),
                "MB"
            )

    except psutil.Error:
        pass

PID: 4892 RAM: 259.16 MB
PID: 14968 RAM: 79.23 MB
PID: 17204 RAM: 10.84 MB
PID: 17748 RAM: 70.75 MB
PID: 20900 RAM: 33.71 MB
PID: 21908 RAM: 48.97 MB
PID: 26900 RAM: 185.57 MB
PID: 27724 RAM: 86.88 MB
PID: 28392 RAM: 317.12 MB
PID: 28652 RAM: 59.08 MB
PID: 29220 RAM: 260.59 MB
PID: 29352 RAM: 152.14 MB
PID: 29720 RAM: 21.53 MB
PID: 29880 RAM: 59.65 MB
PID: 30288 RAM: 137.86 MB
PID: 30416 RAM: 93.98 MB
PID: 30468 RAM: 65.59 MB
PID: 30668 RAM: 88.23 MB
PID: 30892 RAM: 22.11 MB
PID: 32020 RAM: 53.43 MB
PID: 33132 RAM: 31.32 MB
PID: 33548 RAM: 159.3 MB
PID: 35132 RAM: 49.44 MB
PID: 35336 RAM: 329.55 MB
PID: 35828 RAM: 143.3 MB
PID: 36828 RAM: 51.92 MB
PID: 38896 RAM: 318.36 MB


Absolutely. Once you can monitor CPU, RAM, disk, and Ethernet, Python can turn your Windows machine into a small **system/network monitoring lab**.

For your networking-focused learning, these are especially useful:

1. **System uptime and boot time**
```python
import psutil
from datetime import datetime

boot = datetime.fromtimestamp(psutil.boot_time())
print("Boot Time:", boot)
print("Uptime:", datetime.now() - boot)
```

2. **Running processes**
```python
import psutil

for p in psutil.process_iter(["pid", "name", "status"]):
    print(p.info)
```

3. **Listening TCP/UDP ports**
```python
import psutil

for conn in psutil.net_connections(kind="inet"):
    if conn.status == "LISTEN":
        print(
            "Local:", conn.laddr,
            "PID:", conn.pid
        )
```

Run VS Code/terminal as Administrator if access is restricted.

4. **Find which application owns a port**
```python
import psutil

PORT = 443

for conn in psutil.net_connections(kind="inet"):
    if conn.laddr and conn.laddr.port == PORT:
        print("PID:", conn.pid)

        if conn.pid:
            try:
                print("Process:", psutil.Process(conn.pid).name())
            except psutil.Error:
                pass
```

This is similar to:

```powershell
netstat -ano
```

5. **Check your IP addresses**
```python
import psutil

for interface, addresses in psutil.net_if_addrs().items():
    print(f"\n{interface}")

    for addr in addresses:
        print(" ", addr.address)
```

6. **Check interface status and speed**
```python
import psutil

stats = psutil.net_if_stats()

for name, data in stats.items():
    print(
        name,
        "UP:" if data.isup else "DOWN:",
        data.speed,
        "Mbps"
    )
```

7. **Ping monitoring**

Useful for monitoring EVE-NG, routers, gateways, or public destinations:

```python
import subprocess

hosts = [
    "8.8.8.8",
    "1.1.1.1",
    "192.168.32.128"
]

for host in hosts:

    result = subprocess.run(
        ["ping", "-n", "1", host],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print(host, "UP")
    else:
        print(host, "DOWN")
```

8. **TCP port connectivity test**

Python equivalent of:

```powershell
Test-NetConnection 8.8.8.8 -Port 443
```

```python
import socket

host = "8.8.8.8"
port = 443

try:
    connection = socket.create_connection(
        (host, port),
        timeout=3
    )

    print(f"{host}:{port} reachable")
    connection.close()

except Exception as error:
    print(f"{host}:{port} failed")
    print(error)
```

9. **DNS resolution test**
```python
import socket

hostname = "google.com"

try:
    ip = socket.gethostbyname(hostname)

    print("Hostname :", hostname)
    print("IP       :", ip)

except socket.gaierror:
    print("DNS resolution failed")
```

10. **Check established TCP connections**
```python
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status == "ESTABLISHED":

        print(
            conn.laddr,
            " --> ",
            conn.raddr,
            "PID:",
            conn.pid
        )
```

This is particularly useful for learning how applications like **Chrome, Teams, VS Code, and ChatGPT** establish network connections.

11. **Battery information** if this is a laptop:
```python
import psutil

battery = psutil.sensors_battery()

if battery:
    print("Battery:", battery.percent, "%")
    print("Charging:", battery.power_plugged)
else:
    print("No battery detected")
```

12. **Monitor a particular process**

For example, Chrome:

```python
import psutil

target = "chrome.exe"

for p in psutil.process_iter(
    ["pid", "name", "memory_info"]
):
    try:
        if p.info["name"].lower() == target:

            print(
                "PID:",
                p.info["pid"],
                "RAM:",
                round(
                    p.info["memory_info"].rss / 1024**2,
                    2
                ),
                "MB"
            )

    except psutil.Error:
        pass
```

### A useful progression for you

Since you're learning Python for network engineering, I'd build one **Windows Network/System Health Checker** that produces something like:

```text
==============================
 WINDOWS HEALTH CHECK
==============================

SYSTEM
CPU                 34.2%       OK
Memory              50.1%       OK
Disk Active         5.2%        OK
Disk Free           1120 GB     OK

NETWORK
Ethernet 2          UP
IP                   10.0.9.200
Link Speed           10 Gbps
TX                   9.3 Mbps
RX                   0.48 Mbps

CONNECTIVITY
Default Gateway      PASS
8.8.8.8              PASS
1.1.1.1              PASS
google.com DNS       PASS
TCP 443              PASS

CONNECTIONS
TCP Established      48
TCP Listening        37
UDP Endpoints        62

TOP PROCESSES
brave.exe            6.7% CPU
Taskmgr.exe          3.6% CPU
ChatGPT.exe          1.1% CPU

STATUS
Overall Health       HEALTHY
==============================
```

Then add **timestamps and CSV/log-file output**, so every run creates a record. That becomes a genuinely useful Python network-monitoring project rather than a collection of small scripts.

In [32]:
import psutil

for service in psutil.win_service_iter():
    info = service.as_dict()

    print(
        info["name"],
        info["status"]
    )

ADPSvc stopped
ALG stopped
AppIDSvc stopped
Appinfo running
AppMgmt stopped
AppReadiness stopped
AppVClient stopped
AppXSvc running
ApxSvc stopped
aspnet_state stopped
AssignedAccessManagerSvc stopped
AudioEndpointBuilder running
Audiosrv running
autotimesvc stopped
AxInstSV stopped
AzureMonitorAgent running
BDESVC stopped
BFE running
BITS running
brave stopped
BraveElevationService stopped
bravem stopped
BrokerInfrastructure running
BTAGService stopped
BthAvctpSvc stopped
bthserv stopped
camsvc running
CcmExec running
CDPSvc running
CertPropSvc running
ClickToRunSvc running
ClipSVC stopped
cloudidsvc stopped
CloudManagedDesktopExtension running
CmRcService stopped
com.docker.service stopped
COMSysApp stopped
CoreMessagingRegistrar running
CoworkVMService running
CryptSvc running
CscService stopped
DcomLaunch running
dcsvc stopped
defragsvc stopped
DeviceAssociationService running
DeviceInstall stopped
DevQueryBroker stopped
Dhcp running
diagsvc stopped
DiagTrack running
DialogBlocking

FileNotFoundError: [WinError 2] The system cannot find the file specified: '(originated from QueryServiceConfig2W)'

In [33]:
import psutil

service = psutil.win_service_get("Dnscache")
print(service.as_dict())

{'display_name': 'DNS Client', 'binpath': 'C:\\Windows\\system32\\svchost.exe -k NetworkService -p', 'username': 'NT AUTHORITY\\NetworkService', 'start_type': 'automatic', 'status': 'running', 'pid': 3180, 'name': 'Dnscache', 'description': "The DNS Client service (dnscache) sends Domain Name System (DNS) queries, caches query results, and registers the computer's full name on the network. This service is not stoppable."}


In [34]:
import subprocess

result = subprocess.run(
    ["route", "print"],
    capture_output=True,
    text=True
)

print(result.stdout)

Interface List
105...00 0d 3a fd 68 b8 ......Microsoft Hyper-V Network Adapter #2
 76...00 50 56 c0 00 01 ......VMware Virtual Ethernet Adapter for VMnet1
 38...00 50 56 c0 00 08 ......VMware Virtual Ethernet Adapter for VMnet8
  1...........................Software Loopback Interface 1
111...00 15 5d 71 52 bc ......Hyper-V Virtual Ethernet Adapter

IPv4 Route Table
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0         10.0.0.1       10.0.9.200      6
         10.0.0.0    255.255.128.0         On-link        10.0.9.200    261
       10.0.9.200  255.255.255.255         On-link        10.0.9.200    261
     10.0.127.255  255.255.255.255         On-link        10.0.9.200    261
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
    168.

In [35]:
import subprocess

result = subprocess.run(
    ["arp", "-a"],
    capture_output=True,
    text=True
)

print(result.stdout)


Interface: 192.168.32.1 --- 0x26
  Internet Address      Physical Address      Type
  192.168.32.128        00-0c-29-ab-e9-f0     dynamic   
  192.168.32.254        00-50-56-f2-f5-e5     dynamic   
  192.168.32.255        ff-ff-ff-ff-ff-ff     static    
  224.0.0.22            01-00-5e-00-00-16     static    
  224.0.0.251           01-00-5e-00-00-fb     static    
  224.0.0.252           01-00-5e-00-00-fc     static    
  239.255.255.250       01-00-5e-7f-ff-fa     static    
  255.255.255.255       ff-ff-ff-ff-ff-ff     static    

Interface: 192.168.229.1 --- 0x4c
  Internet Address      Physical Address      Type
  192.168.229.254       00-50-56-f5-25-7f     dynamic   
  192.168.229.255       ff-ff-ff-ff-ff-ff     static    
  224.0.0.22            01-00-5e-00-00-16     static    
  224.0.0.251           01-00-5e-00-00-fb     static    
  224.0.0.252           01-00-5e-00-00-fc     static    
  239.255.255.250       01-00-5e-7f-ff-fa     static    
  255.255.255.255       ff-ff-f

In [36]:
import subprocess

result = subprocess.run(
    ["ipconfig", "/all"],
    capture_output=True,
    text=True
)

print(result.stdout)


Windows IP Configuration

   Host Name . . . . . . . . . . . . : CPC-vyaal-N3A6T
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : f7a5e5c3-cab1-4810-bdbb-207cdd06de9e.globalsecureaccess.local

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : reddog.microsoft.com
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #2
   Physical Address. . . . . . . . . : 00-0D-3A-FD-68-B8
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::6132:4038:d2f8:271e%105(Preferred) 
   IPv4 Address. . . . . . . . . . . : 10.0.9.200(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.128.0
   Lease Obtained. . . . . . . . . . : Saturday, August 29, 2026 7:46:03 PM
   Lease Expires . . . . . . . . . . : Wednesday, October 6, 2162

In [37]:
import subprocess

gateway = "10.0.9.1"

result = subprocess.run(
    ["ping", "-n", "2", gateway],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("Default Gateway: REACHABLE")
else:
    print("Default Gateway: UNREACHABLE")

Default Gateway: REACHABLE


In [ ]:
import subprocess

destination = "8.8.8.8"

result = subprocess.run(
    ["tracert", destination],
    capture_output=True,
    text=True
)

print(result.stdout)

In [1]:
import psutil
from collections import Counter

states = []

for conn in psutil.net_connections(kind="tcp"):
    states.append(conn.status)

counts = Counter(states)

for state, count in counts.items():
    print(f"{state:<20} {count}")

ESTABLISHED          286
TIME_WAIT            81
LISTEN               47
CLOSE_WAIT           3
SYN_SENT             1


In [2]:
import psutil

interfaces = psutil.net_io_counters(pernic=True)

for name, stats in interfaces.items():

    print(f"\n{name}")
    print(f"Packets RX : {stats.packets_recv}")
    print(f"Packets TX : {stats.packets_sent}")
    print(f"Errors RX  : {stats.errin}")
    print(f"Errors TX  : {stats.errout}")
    print(f"Drops RX   : {stats.dropin}")
    print(f"Drops TX   : {stats.dropout}")


Ethernet 2
Packets RX : 5516741
Packets TX : 5799681
Errors RX  : 0
Errors TX  : 0
Drops RX   : 0
Drops TX   : 0

VMware Network Adapter VMnet1
Packets RX : 44
Packets TX : 902
Errors RX  : 0
Errors TX  : 0
Drops RX   : 0
Drops TX   : 0

VMware Network Adapter VMnet8
Packets RX : 63
Packets TX : 3868
Errors RX  : 0
Errors TX  : 0
Drops RX   : 0
Drops TX   : 0

Loopback Pseudo-Interface 1
Packets RX : 0
Packets TX : 0
Errors RX  : 0
Errors TX  : 0
Drops RX   : 0
Drops TX   : 0

vEthernet (Default Switch)
Packets RX : 0
Packets TX : 310
Errors RX  : 0
Errors TX  : 0
Drops RX   : 0
Drops TX   : 0


In [3]:
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status == "ESTABLISHED":

        try:
            process = psutil.Process(conn.pid)
            process_name = process.name()
        except:
            process_name = "Unknown"

        print(
            f"{process_name:<25}",
            f"{conn.laddr} -> {conn.raddr}"
        )

fluent-bit.exe            addr(ip='127.0.0.1', port=56610) -> addr(ip='127.0.0.1', port=56611)
fluent-bit.exe            addr(ip='127.0.0.1', port=56597) -> addr(ip='127.0.0.1', port=56596)
GlobalSecureAccessEngineService.exe addr(ip='10.0.9.200', port=64002) -> addr(ip='20.184.175.12', port=443)
fluent-bit.exe            addr(ip='127.0.0.1', port=56568) -> addr(ip='127.0.0.1', port=56566)
msedgewebview2.exe        addr(ip='10.0.9.200', port=56119) -> addr(ip='52.96.113.242', port=443)
fluent-bit.exe            addr(ip='127.0.0.1', port=56606) -> addr(ip='127.0.0.1', port=56607)
GlobalSecureAccessTunnelingService.exe addr(ip='10.0.9.200', port=61508) -> addr(ip='150.171.15.10', port=443)
chrome.exe                addr(ip='10.0.9.200', port=63683) -> addr(ip='20.42.65.88', port=443)
chrome.exe                addr(ip='10.0.9.200', port=51686) -> addr(ip='108.177.98.188', port=5228)
python3.13.exe            addr(ip='127.0.0.1', port=56657) -> addr(ip='127.0.0.1', port=56656)
fluent-bit.e

In [4]:
import platform

print("Computer :", platform.node())
print("OS       :", platform.system())
print("Release  :", platform.release())
print("Version  :", platform.version())
print("Machine  :", platform.machine())
print("CPU      :", platform.processor())

Computer : CPC-vyaal-N3A6T
OS       : Windows
Release  : 11
Version  : 10.0.26200
Machine  : AMD64
CPU      : Intel64 Family 6 Model 106 Stepping 6, GenuineIntel


In [5]:
import psutil

for user in psutil.users():
    print(
        "User     :", user.name,
        "\nTerminal :", user.terminal,
        "\nHost     :", user.host
    )

User     : v-yaalam 
Terminal : None 
Host     : None


In [6]:
import psutil

cpu = psutil.cpu_percent(interval=1)
memory = psutil.virtual_memory().percent
disk = psutil.disk_usage("C:\\").percent

if cpu > 80:
    print("WARNING: High CPU")
else:
    print("CPU OK")

if memory > 80:
    print("WARNING: High Memory")
else:
    print("Memory OK")

if disk > 85:
    print("WARNING: Disk almost full")
else:
    print("Disk OK")

CPU OK
Memory OK
Disk OK


Yes. Beyond CPU, RAM, disk, network throughput, processes, ports, ping, and DNS, there are several useful **Windows checks you can automate with Python**.

### 1. Check Windows services

Find running/stopped services:

```python
import psutil

for service in psutil.win_service_iter():
    info = service.as_dict()

    print(
        info["name"],
        info["status"]
    )
```

Check a specific service:

```python
import psutil

service = psutil.win_service_get("Dnscache")
print(service.as_dict())
```

Useful for checking services such as DNS Client, DHCP, Windows Update, VMware, etc.

### 2. Check routing table

Python can call Windows commands and parse their output:

```python
import subprocess

result = subprocess.run(
    ["route", "print"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

This is very useful for networking because you can inspect:

```text
Destination
Netmask
Gateway
Interface
Metric
Default route
```

### 3. Check ARP / neighbor table

```python
import subprocess

result = subprocess.run(
    ["arp", "-a"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

You can compare this with:

```powershell
Get-NetNeighbor
```

### 4. Check DNS configuration

```python
import subprocess

result = subprocess.run(
    ["ipconfig", "/all"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

You can eventually parse this to extract only:

```text
Interface
IPv4 address
Subnet mask
Default gateway
DHCP server
DNS servers
MAC address
```

### 5. Check default gateway connectivity

This is a particularly useful health test:

```python
import subprocess

gateway = "10.0.9.1"

result = subprocess.run(
    ["ping", "-n", "2", gateway],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("Default Gateway: REACHABLE")
else:
    print("Default Gateway: UNREACHABLE")
```

Replace the gateway with your actual default gateway.

### 6. Run traceroute from Python

```python
import subprocess

destination = "8.8.8.8"

result = subprocess.run(
    ["tracert", destination],
    capture_output=True,
    text=True
)

print(result.stdout)
```

This gives you the hop-by-hop path.

### 7. Check TCP connection states

This is useful for learning TCP:

```python
import psutil
from collections import Counter

states = []

for conn in psutil.net_connections(kind="tcp"):
    states.append(conn.status)

counts = Counter(states)

for state, count in counts.items():
    print(f"{state:<20} {count}")
```

Example:

```text
ESTABLISHED          48
LISTEN               35
TIME_WAIT            127
CLOSE_WAIT           3
SYN_SENT             1
```

This can actually be useful for troubleshooting. For example, unusually large numbers of `CLOSE_WAIT` connections can point you toward an application that isn't closing sockets properly.

### 8. Check interface errors and drops

Very relevant to network engineering:

```python
import psutil

interfaces = psutil.net_io_counters(pernic=True)

for name, stats in interfaces.items():

    print(f"\n{name}")
    print(f"Packets RX : {stats.packets_recv}")
    print(f"Packets TX : {stats.packets_sent}")
    print(f"Errors RX  : {stats.errin}")
    print(f"Errors TX  : {stats.errout}")
    print(f"Drops RX   : {stats.dropin}")
    print(f"Drops TX   : {stats.dropout}")
```

You could later alert when:

```text
Errors RX > 0
Errors TX > 0
Drops RX > 0
Drops TX > 0
```

Be aware that what Windows exposes through `psutil` can vary by adapter/driver.

### 9. Find established connections and owning applications

This one is particularly interesting:

```python
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status == "ESTABLISHED":

        try:
            process = psutil.Process(conn.pid)
            process_name = process.name()
        except:
            process_name = "Unknown"

        print(
            f"{process_name:<25}",
            f"{conn.laddr} -> {conn.raddr}"
        )
```

You can see things like:

```text
chrome.exe       10.0.9.200:52142 -> 142.250.x.x:443
Teams.exe        10.0.9.200:52301 -> 52.x.x.x:443
Code.exe         10.0.9.200:52442 -> 20.x.x.x:443
```

This is basically a simplified Python version of:

```powershell
netstat -ano
```

### 10. Check environment information

```python
import platform

print("Computer :", platform.node())
print("OS       :", platform.system())
print("Release  :", platform.release())
print("Version  :", platform.version())
print("Machine  :", platform.machine())
print("CPU      :", platform.processor())
```

### 11. Check logged-in users

```python
import psutil

for user in psutil.users():
    print(
        "User     :", user.name,
        "\nTerminal :", user.terminal,
        "\nHost     :", user.host
    )
```

### 12. Check system resource thresholds

You can turn your scripts into actual monitoring logic:

```python
import psutil

cpu = psutil.cpu_percent(interval=1)
memory = psutil.virtual_memory().percent
disk = psutil.disk_usage("C:\\").percent

if cpu > 80:
    print("WARNING: High CPU")
else:
    print("CPU OK")

if memory > 80:
    print("WARNING: High Memory")
else:
    print("Memory OK")

if disk > 85:
    print("WARNING: Disk almost full")
else:
    print("Disk OK")
```

### A good next project for you

Rather than creating 20 separate scripts, you could combine everything into one command:

```text
PS C:\Python> python windows_health.py

==================================================
        WINDOWS NETWORK HEALTH CHECK
==================================================

SYSTEM
--------------------------------------------------
Hostname          : SERVER01
Uptime            : 5 days 04:23:12
CPU               : 34.2%       [OK]
Memory            : 50.1%       [OK]
Disk              : 43.8%       [OK]

NETWORK
--------------------------------------------------
Interface         : Ethernet 2
Status            : UP
IPv4              : 10.0.9.200
Gateway           : 10.0.9.1
TX                : 9.31 Mbps
RX                : 0.49 Mbps
RX Errors         : 0
TX Errors         : 0

CONNECTIVITY
--------------------------------------------------
Gateway Ping      : PASS
8.8.8.8 Ping      : PASS
1.1.1.1 Ping      : PASS
google.com DNS    : PASS
TCP/443           : PASS

TCP
--------------------------------------------------
ESTABLISHED       : 48
LISTEN            : 37
TIME_WAIT         : 114
CLOSE_WAIT        : 0

TOP CPU PROCESSES
--------------------------------------------------
brave.exe         : 6.7%
Taskmgr.exe       : 3.6%
ChatGPT.exe       : 1.1%

OVERALL STATUS
--------------------------------------------------
HEALTHY
==================================================
```

That would be a strong practical **Python + Windows + Network Engineering** project because the next step could be logging each run to CSV/JSON and comparing health checks over time.

In [7]:
import subprocess

print(subprocess.run(
    ["route", "print", "0.0.0.0"],
    capture_output=True,
    text=True
).stdout)

Interface List
105...00 0d 3a fd 68 b8 ......Microsoft Hyper-V Network Adapter #2
 76...00 50 56 c0 00 01 ......VMware Virtual Ethernet Adapter for VMnet1
 38...00 50 56 c0 00 08 ......VMware Virtual Ethernet Adapter for VMnet8
  1...........................Software Loopback Interface 1
111...00 15 5d 71 52 bc ......Hyper-V Virtual Ethernet Adapter

IPv4 Route Table
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0         10.0.0.1       10.0.9.200      6
Persistent Routes:
  None

IPv6 Route Table
Active Routes:
  None
Persistent Routes:
  None



In [8]:
import socket
import time

host = "google.com"

start = time.perf_counter()
ip = socket.gethostbyname(host)
elapsed = (time.perf_counter() - start) * 1000

print("Hostname :", host)
print("IP       :", ip)
print(f"DNS Time : {elapsed:.2f} ms")

Hostname : google.com
IP       : 142.250.73.110
DNS Time : 10.81 ms


In [9]:
import socket
import time

host = "google.com"
port = 443

start = time.perf_counter()

try:
    sock = socket.create_connection((host, port), timeout=5)

    latency = (time.perf_counter() - start) * 1000

    print("TCP Connection : PASS")
    print(f"TCP Latency    : {latency:.2f} ms")

    sock.close()

except Exception as e:
    print("TCP Connection : FAIL")
    print(e)

TCP Connection : PASS
TCP Latency    : 16.68 ms


In [10]:
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

try:
    s.connect(("8.8.8.8", 80))
    print("Local IP:", s.getsockname()[0])
finally:
    s.close()

Local IP: 10.0.9.200


In [11]:
import subprocess

result = subprocess.run(
    ["netsh", "interface", "ipv4", "show", "subinterfaces"],
    capture_output=True,
    text=True
)

print(result.stdout)


       MTU  MediaSenseState      Bytes In     Bytes Out  Interface
----------  ---------------  ------------  ------------  -------------
4294967295                1             0         12025  Loopback Pseudo-Interface 1
      1500                1             0         24842  vEthernet (Default Switch)
      1500                1    6665087065    8185354583  Ethernet 2
      1500                1          7544         48717  VMware Network Adapter VMnet1
      1500                1          8608         48203  VMware Network Adapter VMnet8




In [12]:
import subprocess

host = "8.8.8.8"

result = subprocess.run(
    ["ping", host, "-f", "-l", "1472"],
    capture_output=True,
    text=True
)

print(result.stdout)

KeyboardInterrupt: 

In [13]:
import subprocess

result = subprocess.run(
    ["ipconfig", "/displaydns"],
    capture_output=True,
    text=True
)

print(result.stdout)


Windows IP Configuration

    yt3.googleusercontent.com
    ----------------------------------------
    Record Name . . . . . : yt3.googleusercontent.com
    Record Type . . . . . : 1
    Time To Live  . . . . : 161
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 142.251.46.65


    Record Name . . . . . : yt3.googleusercontent.com
    Record Type . . . . . : 1
    Time To Live  . . . . : 161
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 142.250.73.65


    Record Name . . . . . : yt3.googleusercontent.com
    Record Type . . . . . : 1
    Time To Live  . . . . : 161
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 142.250.73.97


    Record Name . . . . . : yt3.googleusercontent.com
    Record Type . . . . . : 1
    Time To Live  . . . . : 161
    Data Length . . . . . : 4
    Section . . . . . . . : Answer
    A (Host) Record . . . : 142.250.73.129

In [14]:
import subprocess

result = subprocess.run(
    ["netsh", "advfirewall", "show", "allprofiles"],
    capture_output=True,
    text=True
)

print(result.stdout)


Domain Profile Settings: 
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Enable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


Private Profile Settings: 
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/

In [15]:
import subprocess

result = subprocess.run(
    ["netsh", "wlan", "show", "interfaces"],
    capture_output=True,
    text=True
)

print(result.stdout)

The Wireless AutoConfig Service (wlansvc) is not running.



In [16]:
import psutil

net = psutil.net_io_counters()

print("Packets Sent     :", net.packets_sent)
print("Packets Received :", net.packets_recv)
print("Receive Errors   :", net.errin)
print("Transmit Errors  :", net.errout)
print("Receive Drops    :", net.dropin)
print("Transmit Drops   :", net.dropout)

Packets Sent     : 5992158
Packets Received : 5563856
Receive Errors   : 0
Transmit Errors  : 0
Receive Drops    : 0
Transmit Drops   : 0


In [17]:
import psutil

data = []

for p in psutil.process_iter(["pid", "name", "num_threads"]):
    try:
        data.append(p.info)
    except psutil.Error:
        pass

data.sort(
    key=lambda x: x["num_threads"],
    reverse=True
)

for p in data[:15]:
    print(
        p["pid"],
        p["name"],
        p["num_threads"]
    )

4 System 446
5440 GlobalSecureAccessTunnelingService.exe 208
2920 svchost.exe 163
3980 MemCompression 122
19792 ms-teams.exe 84
5380 MsMpEng.exe 78
24020 msedge.exe 76
17336 Code.exe 73
2180 copilotapp.exe 67
13764 MonAgentCore.exe 62
17608 ONENOTE.EXE 58
464 ChatGPT.exe 57
3036 MonAgentCore.exe 57
11820 msedgewebview2.exe 57
30964 msedgewebview2.exe 57


In [18]:
import psutil

processes = []

for p in psutil.process_iter(["pid", "name"]):
    try:
        processes.append(
            (
                p.pid,
                p.name(),
                p.num_handles()
            )
        )
    except psutil.Error:
        pass

processes.sort(
    key=lambda x: x[2],
    reverse=True
)

for pid, name, handles in processes[:15]:
    print(pid, name, handles)

4 System 12588
14088 explorer.exe 3597
32968 brave.exe 2869
24020 msedge.exe 2492
1664 lsass.exe 2478
28392 chrome.exe 2461
3064 svchost.exe 2155
17608 ONENOTE.EXE 2026
464 ChatGPT.exe 2011
10348 Microsoft.Management.Services.IntuneWindowsAgent.exe 1907
16768 WhatsApp.Root.exe 1862
1848 svchost.exe 1842
19816 brave.exe 1831
2180 copilotapp.exe 1814
5380 MsMpEng.exe 1712


In [19]:
import psutil

swap = psutil.swap_memory()

print(f"Total : {swap.total / 1024**3:.2f} GB")
print(f"Used  : {swap.used / 1024**3:.2f} GB")
print(f"Free  : {swap.free / 1024**3:.2f} GB")
print(f"Usage : {swap.percent}%")

Total : 9.50 GB
Used  : 0.13 GB
Free  : 9.37 GB
Usage : 1.3%


In [20]:
import psutil

for disk in psutil.disk_partitions():

    print("Device     :", disk.device)
    print("Mount Point:", disk.mountpoint)
    print("Filesystem :", disk.fstype)
    print("Options    :", disk.opts)
    print()

Device     : C:\
Mount Point: C:\
Filesystem : NTFS
Options    : rw,fixed



In [21]:
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status != "ESTABLISHED":
        continue

    try:
        process = psutil.Process(conn.pid)
        name = process.name()
    except:
        name = "Unknown"

    print(
        f"{name:<25}",
        f"{conn.laddr.ip}:{conn.laddr.port}",
        "-->",
        f"{conn.raddr.ip}:{conn.raddr.port}"
    )

CcmExec.exe               10.0.9.200:53144 --> 52.148.48.135:443
fluent-bit.exe            127.0.0.1:56610 --> 127.0.0.1:56611
fluent-bit.exe            127.0.0.1:56597 --> 127.0.0.1:56596
MicrosoftStartFeedProvider.exe 10.0.9.200:58299 --> 104.96.163.85:443
GlobalSecureAccessEngineService.exe 10.0.9.200:64002 --> 20.184.175.12:443
fluent-bit.exe            127.0.0.1:56568 --> 127.0.0.1:56566
msedgewebview2.exe        10.0.9.200:56119 --> 52.96.113.242:443
fluent-bit.exe            127.0.0.1:56606 --> 127.0.0.1:56607
GlobalSecureAccessTunnelingService.exe 10.0.9.200:61508 --> 150.171.15.10:443
chrome.exe                10.0.9.200:51686 --> 108.177.98.188:5228
python3.13.exe            127.0.0.1:56657 --> 127.0.0.1:56656
fluent-bit.exe            127.0.0.1:56585 --> 127.0.0.1:56584
vmware.exe                ::1:61385 --> ::1:61384
MpDefenderCoreService.exe 10.0.9.200:58322 --> 4.150.223.100:443
fluent-bit.exe            127.0.0.1:56544 --> 127.0.0.1:56545
fluent-bit.exe            127.0

In [22]:
import subprocess

print(
    subprocess.run(
        ["netstat", "-s"],
        capture_output=True,
        text=True
    ).stdout
)


IPv4 Statistics

  Packets Received                   = 5103369
  Received Header Errors             = 0
  Received Address Errors            = 4
  Datagrams Forwarded                = 0
  Unknown Protocols Received         = 0
  Received Packets Discarded         = 294
  Received Packets Delivered         = 5106514
  Output Requests                    = 8205447
  Routing Discards                   = 0
  Discarded Output Packets           = 3085
  Output Packet No Route             = 3
  Reassembly Required                = 0
  Reassembly Successful              = 0
  Reassembly Failures                = 0
  Datagrams Successfully Fragmented  = 0
  Datagrams Failing Fragmentation    = 0
  Fragments Created                  = 0

IPv6 Statistics

  Packets Received                   = 0
  Received Header Errors             = 0
  Received Address Errors            = 0
  Datagrams Forwarded                = 0
  Unknown Protocols Received         = 0
  Received Packets Discarded         = 

In [23]:
import subprocess

command = [
    "powershell",
    "-Command",
    "Get-WinEvent -LogName System -MaxEvents 20 | "
    "Select TimeCreated,Id,LevelDisplayName,Message"
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True
)

print(result.stdout)


TimeCreated             Id LevelDisplayName Message                                                                    
-----------             -- ---------------- -------                                                                    
8/30/2026 1:13:51 AM     4 Information      Service stopped.                                                           
8/30/2026 1:13:25 AM     3 Information      Service started.                                                           
8/30/2026 1:09:35 AM  7040 Information      The start type of the Background Intelligent Transfer Service service wa...
8/30/2026 1:08:50 AM     4 Information      Service stopped.                                                           
8/30/2026 1:08:23 AM     3 Information      Service started.                                                           
8/30/2026 1:08:19 AM  7040 Information      The start type of the Background Intelligent Transfer Service service wa...
8/30/2026 1:03:50 AM     4 Information 

Definitely. Since you've already covered CPU, memory, disk, Ethernet, processes, ports, DNS, ping, routing, ARP, services, and TCP states, here are some more advanced checks that are useful for **Windows/network troubleshooting with Python**.

1. **Default route and gateway**
```python
import subprocess

print(subprocess.run(
    ["route", "print", "0.0.0.0"],
    capture_output=True,
    text=True
).stdout)
```

2. **DNS lookup with timing**
```python
import socket
import time

host = "google.com"

start = time.perf_counter()
ip = socket.gethostbyname(host)
elapsed = (time.perf_counter() - start) * 1000

print("Hostname :", host)
print("IP       :", ip)
print(f"DNS Time : {elapsed:.2f} ms")
```

This helps distinguish **DNS slowness** from general network slowness.

3. **TCP connection latency**
```python
import socket
import time

host = "google.com"
port = 443

start = time.perf_counter()

try:
    sock = socket.create_connection((host, port), timeout=5)

    latency = (time.perf_counter() - start) * 1000

    print("TCP Connection : PASS")
    print(f"TCP Latency    : {latency:.2f} ms")

    sock.close()

except Exception as e:
    print("TCP Connection : FAIL")
    print(e)
```

4. **Public vs local IP**

Local IP:

```python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

try:
    s.connect(("8.8.8.8", 80))
    print("Local IP:", s.getsockname()[0])
finally:
    s.close()
```

This is useful for identifying which source IP Windows selects for outbound traffic.

5. **Network adapter MTU**
```python
import subprocess

result = subprocess.run(
    ["netsh", "interface", "ipv4", "show", "subinterfaces"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

You should see something like:

```text
MTU        MediaSenseState   Bytes In   Bytes Out   Interface
1500       1                 ...        ...         Ethernet 2
```

6. **Test MTU / fragmentation**

Very useful for VPN, tunnel, and network troubleshooting:

```python
import subprocess

host = "8.8.8.8"

result = subprocess.run(
    ["ping", host, "-f", "-l", "1472"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

On Ethernet:

```text
1472 payload
+ 20 byte IPv4 header
+ 8 byte ICMP header
= 1500-byte packet
```

If fragmentation is required, progressively lower `1472`.

7. **Windows DNS cache**
```python
import subprocess

result = subprocess.run(
    ["ipconfig", "/displaydns"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

Useful for seeing what DNS records your machine has cached.

8. **Firewall profiles**

```python
import subprocess

result = subprocess.run(
    ["netsh", "advfirewall", "show", "allprofiles"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

This lets Python check whether Windows Firewall is enabled for Domain, Private, and Public profiles.

9. **Check active Wi-Fi information**

If the machine uses Wi-Fi:

```python
import subprocess

result = subprocess.run(
    ["netsh", "wlan", "show", "interfaces"],
    capture_output=True,
    text=True
)

print(result.stdout)
```

This can expose useful information such as signal strength, channel, radio type, and link rates.

10. **Check packet counters**

```python
import psutil

net = psutil.net_io_counters()

print("Packets Sent     :", net.packets_sent)
print("Packets Received :", net.packets_recv)
print("Receive Errors   :", net.errin)
print("Transmit Errors  :", net.errout)
print("Receive Drops    :", net.dropin)
print("Transmit Drops   :", net.dropout)
```

11. **Check process thread counts**

High thread counts can help identify problematic applications:

```python
import psutil

data = []

for p in psutil.process_iter(["pid", "name", "num_threads"]):
    try:
        data.append(p.info)
    except psutil.Error:
        pass

data.sort(
    key=lambda x: x["num_threads"],
    reverse=True
)

for p in data[:15]:
    print(
        p["pid"],
        p["name"],
        p["num_threads"]
    )
```

12. **Check process handle counts on Windows**

```python
import psutil

processes = []

for p in psutil.process_iter(["pid", "name"]):
    try:
        processes.append(
            (
                p.pid,
                p.name(),
                p.num_handles()
            )
        )
    except psutil.Error:
        pass

processes.sort(
    key=lambda x: x[2],
    reverse=True
)

for pid, name, handles in processes[:15]:
    print(pid, name, handles)
```

This can help investigate **handle leaks**.

13. **Check swap/page-file usage**

```python
import psutil

swap = psutil.swap_memory()

print(f"Total : {swap.total / 1024**3:.2f} GB")
print(f"Used  : {swap.used / 1024**3:.2f} GB")
print(f"Free  : {swap.free / 1024**3:.2f} GB")
print(f"Usage : {swap.percent}%")
```

High paging combined with high RAM utilization can explain performance problems.

14. **Check disk partitions**

```python
import psutil

for disk in psutil.disk_partitions():

    print("Device     :", disk.device)
    print("Mount Point:", disk.mountpoint)
    print("Filesystem :", disk.fstype)
    print("Options    :", disk.opts)
    print()
```

15. **Check established connections by process**

This is one of the most useful networking exercises:

```python
import psutil

for conn in psutil.net_connections(kind="tcp"):

    if conn.status != "ESTABLISHED":
        continue

    try:
        process = psutil.Process(conn.pid)
        name = process.name()
    except:
        name = "Unknown"

    print(
        f"{name:<25}",
        f"{conn.laddr.ip}:{conn.laddr.port}",
        "-->",
        f"{conn.raddr.ip}:{conn.raddr.port}"
    )
```

You can observe exactly where applications such as Chrome, VS Code, Teams, and ChatGPT are connecting.

16. **Check TCP statistics**

Python can execute Windows `netstat`:

```python
import subprocess

print(
    subprocess.run(
        ["netstat", "-s"],
        capture_output=True,
        text=True
    ).stdout
)
```

This is excellent for networking because it exposes statistics such as TCP segments, connection failures, resets, UDP datagrams, and IP statistics.

17. **Check Windows event logs**

For example, recent system errors:

```python
import subprocess

command = [
    "powershell",
    "-Command",
    "Get-WinEvent -LogName System -MaxEvents 20 | "
    "Select TimeCreated,Id,LevelDisplayName,Message"
]

result = subprocess.run(
    command,
    capture_output=True,
    text=True
)

print(result.stdout)
```

This moves you beyond resource monitoring into actual **Windows troubleshooting**.

### A good Python troubleshooting toolkit

You now have enough individual checks to build a fairly serious tool:

```text
python windows_health.py

========== SYSTEM ==========
CPU                  PASS    31%
Memory               PASS    50%
Disk                  PASS    5% active
Page File             PASS    12%
Uptime                        5d 03h

========== NETWORK =========
Ethernet 2            UP
IPv4                  10.0.9.200
MTU                   1500
RX                    488 Kbps
TX                    9.3 Mbps
RX Errors             0
TX Errors             0

========== CONNECTIVITY ====
Default Gateway       PASS
Internet Ping         PASS
DNS Resolution        PASS    22 ms
TCP/443               PASS    31 ms
MTU 1500              PASS

========== TCP ==============
ESTABLISHED           47
LISTEN                38
TIME_WAIT             91
CLOSE_WAIT            0

========== WINDOWS ==========
Firewall              ENABLED
Critical Events       0
System Errors         2

========== HEALTH ===========
Overall               HEALTHY
```

For a network engineer, I'd next add **packet-loss percentage, average/min/max latency, DNS response time, TCP handshake time, traceroute, MTU discovery, interface errors, and continuous logging to CSV**. That starts looking much more like a real endpoint/network diagnostic agent rather than just a Task Manager replacement.

In [24]:
import subprocess

target = "8.8.8.8"

payload_sizes = [
    1472,   # MTU 1500
    2000,
    4000,
    8000,
    8972    # MTU 9000
]

print(f"Testing jumbo packets to {target}")
print("=" * 60)

for size in payload_sizes:

    print(f"\nTesting payload: {size} bytes")

    command = [
        "ping",
        target,
        "-n", "2",
        "-f",
        "-l", str(size)
    ]

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.returncode == 0:
        print(f"RESULT: PASS - {size} byte payload succeeded")
    else:
        print(f"RESULT: FAIL - {size} byte payload failed")

Testing jumbo packets to 8.8.8.8

Testing payload: 1472 bytes

Pinging 8.8.8.8 with 1472 bytes of data:
Request timed out.
Request timed out.

Ping statistics for 8.8.8.8:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),

RESULT: FAIL - 1472 byte payload failed

Testing payload: 2000 bytes

Pinging 8.8.8.8 with 2000 bytes of data:
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.

Ping statistics for 8.8.8.8:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),

RESULT: FAIL - 2000 byte payload failed

Testing payload: 4000 bytes

Pinging 8.8.8.8 with 4000 bytes of data:
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.

Ping statistics for 8.8.8.8:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),

RESULT: FAIL - 4000 byte payload failed

Testing payload: 8000 bytes

Pinging 8.8.8.8 with 8000 bytes of data:
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.

Pi

In [25]:
import subprocess

target = "8.8.8.8"

payload_sizes = [
    1472,   # MTU 1500
    2000,
    4000,
    8000,
    8972    # MTU 9000
]

print(f"Testing jumbo packets to {target}")
print("=" * 60)

for size in payload_sizes:

    print(f"\nTesting payload: {size} bytes")

    command = [
        "ping",
        target,
        "-n", "5",
        "-f",
        "-l", str(size)
    ]

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.returncode == 0:
        print(f"RESULT: PASS - {size} byte payload succeeded")
    else:
        print(f"RESULT: FAIL - {size} byte payload failed")

Testing jumbo packets to 8.8.8.8

Testing payload: 1472 bytes

Pinging 8.8.8.8 with 1472 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 8.8.8.8:
    Packets: Sent = 5, Received = 0, Lost = 5 (100% loss),

RESULT: FAIL - 1472 byte payload failed

Testing payload: 2000 bytes

Pinging 8.8.8.8 with 2000 bytes of data:
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.

Ping statistics for 8.8.8.8:
    Packets: Sent = 5, Received = 0, Lost = 5 (100% loss),

RESULT: FAIL - 2000 byte payload failed

Testing payload: 4000 bytes

Pinging 8.8.8.8 with 4000 bytes of data:
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fragmented but DF set.
Packet needs to be fr

In [26]:
import subprocess

target = "192.168.32.128"

low = 0
high = 8972

largest_payload = 0

while low <= high:

    size = (low + high) // 2

    result = subprocess.run(
        [
            "ping",
            target,
            "-n", "1",
            "-f",
            "-l", str(size)
        ],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:

        print(f"PASS: {size} bytes")

        largest_payload = size
        low = size + 1

    else:

        print(f"FAIL: {size} bytes")
        high = size - 1


mtu = largest_payload + 28

print("\n==============================")
print(f"Largest ICMP payload : {largest_payload}")
print(f"Estimated IPv4 MTU   : {mtu}")
print("==============================")

FAIL: 4486 bytes
FAIL: 2242 bytes
PASS: 1120 bytes
FAIL: 1681 bytes
PASS: 1400 bytes
FAIL: 1540 bytes
PASS: 1470 bytes
FAIL: 1505 bytes
FAIL: 1487 bytes
FAIL: 1478 bytes
FAIL: 1474 bytes
PASS: 1472 bytes
FAIL: 1473 bytes

Largest ICMP payload : 1472
Estimated IPv4 MTU   : 1500


Yes. On Windows, the simplest jumbo-frame test from Python is to call `ping` with the **Don't Fragment** flag and a large payload.

For a standard Ethernet MTU of **1500**, the largest ICMP payload is usually `1472` bytes:

```text
1472 payload + 20-byte IPv4 header + 8-byte ICMP header = 1500
```

For a jumbo MTU of **9000**, the corresponding IPv4 ICMP payload is typically:

```text
8972 + 20 + 8 = 9000
```

Use this Python script:

```python
import subprocess

target = "8.8.8.8"

payload_sizes = [
    1472,   # MTU 1500
    2000,
    4000,
    8000,
    8972    # MTU 9000
]

print(f"Testing jumbo packets to {target}")
print("=" * 60)

for size in payload_sizes:

    print(f"\nTesting payload: {size} bytes")

    command = [
        "ping",
        target,
        "-n", "2",
        "-f",
        "-l", str(size)
    ]

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.returncode == 0:
        print(f"RESULT: PASS - {size} byte payload succeeded")
    else:
        print(f"RESULT: FAIL - {size} byte payload failed")
```

You may see a result like this for a normal 1500-MTU path:

```text
Testing jumbo packets to 8.8.8.8
============================================================

Testing payload: 1472 bytes

Pinging 8.8.8.8 with 1472 bytes of data:
Reply from 8.8.8.8: bytes=1472 time=18ms TTL=117
Reply from 8.8.8.8: bytes=1472 time=17ms TTL=117

Ping statistics for 8.8.8.8:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss)

RESULT: PASS - 1472 byte payload succeeded


Testing payload: 2000 bytes

Pinging 8.8.8.8 with 2000 bytes of data:
Packet needs to be fragmented but DF set.

RESULT: FAIL - 2000 byte payload failed


Testing payload: 8972 bytes

Packet needs to be fragmented but DF set.

RESULT: FAIL - 8972 byte payload failed
```

That would mean the end-to-end path does **not** support jumbo frames.

For testing a device inside your lab where you expect MTU 9000, change the target:

```python
target = "192.168.32.128"
```

and test:

```python
payload_sizes = [
    1472,
    4000,
    8000,
    8972
]
```

If jumbo frames are working end-to-end, you'd expect something like:

```text
Testing payload: 8972 bytes

Pinging 192.168.32.128 with 8972 bytes of data:
Reply from 192.168.32.128: bytes=8972 time<1ms TTL=64
Reply from 192.168.32.128: bytes=8972 time<1ms TTL=64

Packets: Sent = 2, Received = 2, Lost = 0 (0% loss)

RESULT: PASS - 8972 byte payload succeeded
```

You can also make Python automatically find the **maximum working MTU**:

```python
import subprocess

target = "192.168.32.128"

low = 0
high = 8972

largest_payload = 0

while low <= high:

    size = (low + high) // 2

    result = subprocess.run(
        [
            "ping",
            target,
            "-n", "1",
            "-f",
            "-l", str(size)
        ],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:

        print(f"PASS: {size} bytes")

        largest_payload = size
        low = size + 1

    else:

        print(f"FAIL: {size} bytes")
        high = size - 1


mtu = largest_payload + 28

print("\n==============================")
print(f"Largest ICMP payload : {largest_payload}")
print(f"Estimated IPv4 MTU   : {mtu}")
print("==============================")
```

Example output:

```text
PASS: 4486 bytes
PASS: 6729 bytes
PASS: 7851 bytes
PASS: 8412 bytes
PASS: 8692 bytes
PASS: 8832 bytes
PASS: 8902 bytes
PASS: 8937 bytes
PASS: 8955 bytes
PASS: 8964 bytes
PASS: 8968 bytes
PASS: 8970 bytes
PASS: 8971 bytes
PASS: 8972 bytes

==============================
Largest ICMP payload : 8972
Estimated IPv4 MTU   : 9000
==============================
```

That is a very useful script for validating jumbo-frame support across your EVE-NG, VMware, Hyper-V, or physical lab path.

In [27]:
import subprocess

target = "8.8.8.8"

result = subprocess.run(
    ["ping", "-n", "10", target],
    capture_output=True,
    text=True
)

print(result.stdout)


Pinging 8.8.8.8 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 8.8.8.8:
    Packets: Sent = 10, Received = 0, Lost = 10 (100% loss),



In [28]:
import subprocess

target = "8.8.8.8"

sizes = [32, 128, 512, 1024, 1400, 1472]

for size in sizes:

    result = subprocess.run(
        ["ping", "-n", "2", "-f", "-l", str(size), target],
        capture_output=True,
        text=True
    )

    status = "PASS" if result.returncode == 0 else "FAIL"

    print(f"Payload {size:4} bytes : {status}")

Payload   32 bytes : FAIL
Payload  128 bytes : FAIL
Payload  512 bytes : FAIL
Payload 1024 bytes : FAIL
Payload 1400 bytes : FAIL
Payload 1472 bytes : FAIL


In [29]:
import socket
import time

target = "google.com"
ports = [80, 443]

for port in ports:

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (target, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        print(
            f"TCP {target}:{port} "
            f"PASS - {latency:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(
            f"TCP {target}:{port} FAIL - {error}"
        )

TCP google.com:80 PASS - 20.78 ms
TCP google.com:443 PASS - 30.56 ms


In [ ]:
import socket

sock = socket.socket(
    socket.AF_INET,
    socket.SOCK_DGRAM
)

sock.bind(("0.0.0.0", 5005))

print("Waiting for UDP packets...")

while True:

    data, address = sock.recvfrom(4096)

    print(
        f"Received from {address}: "
        f"{data.decode(errors='replace')}"
    )

Waiting for UDP packets...


In [1]:
import socket

target = "192.168.1.10"
port = 5005

sock = socket.socket(
    socket.AF_INET,
    socket.SOCK_DGRAM
)

message = b"Python UDP Test"

sock.sendto(
    message,
    (target, port)
)

print("UDP packet sent")

UDP packet sent


In [ ]:
import socket

server = socket.socket(
    socket.AF_INET,
    socket.SOCK_STREAM
)

server.bind(("0.0.0.0", 5000))
server.listen(5)

print("Listening on TCP/5000")

while True:

    connection, address = server.accept()

    print("Connection from:", address)

    data = connection.recv(1024)

    print("Received:", data.decode(errors="replace"))

    connection.sendall(b"Message received")

    connection.close()

Listening on TCP/5000


In [1]:
import socket
import time

hosts = [
    "google.com",
    "microsoft.com",
    "github.com"
]

for host in hosts:

    start = time.perf_counter()

    try:

        addresses = socket.gethostbyname_ex(host)

        elapsed = (
            time.perf_counter() - start
        ) * 1000

        print(
            f"{host:<20}"
            f"{addresses[2]} "
            f"{elapsed:.2f} ms"
        )

    except socket.gaierror:
        print(host, "DNS FAILED")

google.com          ['142.251.46.78'] 11.60 ms
microsoft.com       ['150.171.110.146'] 4.39 ms
github.com          ['140.82.116.3'] 4.02 ms


In [2]:
import subprocess

target = "8.8.8.8"

low = 1200
high = 8972
largest = 0

while low <= high:

    size = (low + high) // 2

    result = subprocess.run(
        [
            "ping",
            "-n", "1",
            "-f",
            "-l", str(size),
            target
        ],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:

        largest = size
        low = size + 1

    else:
        high = size - 1


print("Largest ICMP payload :", largest)
print("Estimated IPv4 MTU   :", largest + 28)

Largest ICMP payload : 0
Estimated IPv4 MTU   : 28


In [3]:
import subprocess
import re

target = "8.8.8.8"

result = subprocess.run(
    ["ping", "-n", "20", target],
    capture_output=True,
    text=True
)

times = re.findall(
    r"time[=<](\d+)ms",
    result.stdout
)

times = [int(x) for x in times]

if times:

    differences = [
        abs(times[i] - times[i-1])
        for i in range(1, len(times))
    ]

    jitter = sum(differences) / len(differences)

    print("Samples :", times)
    print("Min     :", min(times), "ms")
    print("Max     :", max(times), "ms")
    print("Average :", sum(times)/len(times), "ms")
    print("Jitter  :", round(jitter, 2), "ms")

Yes. There are many useful **packet/network tests you can build with Python** on your Windows machine beyond jumbo packets. For network-engineering practice, I would focus on tests that help diagnose real connectivity problems.

Here are 10 good ones to try.

1. **Packet loss + latency test** — send multiple ICMP pings and calculate loss.

```python
import subprocess

target = "8.8.8.8"

result = subprocess.run(
    ["ping", "-n", "10", target],
    capture_output=True,
    text=True
)

print(result.stdout)
```

You'll get results such as:

```text
Packets: Sent = 10, Received = 10, Lost = 0 (0% loss)

Minimum = 14ms
Maximum = 21ms
Average = 17ms
```

This is one of the first tests I'd run during a connectivity issue.

2. **Different packet-size testing** — useful for detecting MTU problems.

```python
import subprocess

target = "8.8.8.8"

sizes = [32, 128, 512, 1024, 1400, 1472]

for size in sizes:

    result = subprocess.run(
        ["ping", "-n", "2", "-f", "-l", str(size), target],
        capture_output=True,
        text=True
    )

    status = "PASS" if result.returncode == 0 else "FAIL"

    print(f"Payload {size:4} bytes : {status}")
```

Example:

```text
Payload   32 bytes : PASS
Payload  128 bytes : PASS
Payload  512 bytes : PASS
Payload 1024 bytes : PASS
Payload 1400 bytes : PASS
Payload 1472 bytes : PASS
```

3. **TCP handshake test** — check whether a particular destination port can be reached.

```python
import socket
import time

target = "google.com"
ports = [80, 443]

for port in ports:

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (target, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        print(
            f"TCP {target}:{port} "
            f"PASS - {latency:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(
            f"TCP {target}:{port} FAIL - {error}"
        )
```

Example:

```text
TCP google.com:80  PASS - 21.45 ms
TCP google.com:443 PASS - 18.72 ms
```

This is similar to:

```powershell
Test-NetConnection google.com -Port 443
```

4. **Traceroute testing** — see where packets travel.

```python
import subprocess

target = "8.8.8.8"

result = subprocess.run(
    ["tracert", target],
    capture_output=True,
    text=True
)

print(result.stdout)
```

Example:

```text
1     1 ms     1 ms     1 ms    10.0.9.1
2     4 ms     3 ms     4 ms    10.x.x.x
3    11 ms    10 ms    12 ms    ...
4    17 ms    16 ms    17 ms    8.8.8.8
```

This is useful for identifying **where latency or packet loss appears along a path**, although intermediate routers may rate-limit or block traceroute responses.

5. **UDP send/receive testing** — good for understanding connectionless traffic.

Receiver:

```python
import socket

sock = socket.socket(
    socket.AF_INET,
    socket.SOCK_DGRAM
)

sock.bind(("0.0.0.0", 5005))

print("Waiting for UDP packets...")

while True:

    data, address = sock.recvfrom(4096)

    print(
        f"Received from {address}: "
        f"{data.decode(errors='replace')}"
    )
```

Sender:

```python
import socket

target = "192.168.1.10"
port = 5005

sock = socket.socket(
    socket.AF_INET,
    socket.SOCK_DGRAM
)

message = b"Python UDP Test"

sock.sendto(
    message,
    (target, port)
)

print("UDP packet sent")
```

Use this only against machines/services you control or have permission to test.

6. **TCP server/client packet testing** — excellent networking practice.

Server:

```python
import socket

server = socket.socket(
    socket.AF_INET,
    socket.SOCK_STREAM
)

server.bind(("0.0.0.0", 5000))
server.listen(5)

print("Listening on TCP/5000")

while True:

    connection, address = server.accept()

    print("Connection from:", address)

    data = connection.recv(1024)

    print("Received:", data.decode(errors="replace"))

    connection.sendall(b"Message received")

    connection.close()
```

Client:

```python
import socket

client = socket.create_connection(
    ("192.168.1.10", 5000),
    timeout=5
)

client.sendall(b"Network test")

response = client.recv(1024)

print(response.decode())

client.close()
```

This lets you observe the complete:

```text
SYN
SYN-ACK
ACK
DATA
ACK
FIN
```

sequence in Wireshark.

7. **DNS packet/query testing** — test DNS resolution and response time.

```python
import socket
import time

hosts = [
    "google.com",
    "microsoft.com",
    "github.com"
]

for host in hosts:

    start = time.perf_counter()

    try:

        addresses = socket.gethostbyname_ex(host)

        elapsed = (
            time.perf_counter() - start
        ) * 1000

        print(
            f"{host:<20}"
            f"{addresses[2]} "
            f"{elapsed:.2f} ms"
        )

    except socket.gaierror:
        print(host, "DNS FAILED")
```

8. **Path MTU discovery** — automatically determine the largest packet that can traverse the path without IPv4 fragmentation.

```python
import subprocess

target = "8.8.8.8"

low = 1200
high = 8972
largest = 0

while low <= high:

    size = (low + high) // 2

    result = subprocess.run(
        [
            "ping",
            "-n", "1",
            "-f",
            "-l", str(size),
            target
        ],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:

        largest = size
        low = size + 1

    else:
        high = size - 1


print("Largest ICMP payload :", largest)
print("Estimated IPv4 MTU   :", largest + 28)
```

Typical Internet result:

```text
Largest ICMP payload : 1472
Estimated IPv4 MTU   : 1500
```

In a jumbo-enabled lab you might see:

```text
Largest ICMP payload : 8972
Estimated IPv4 MTU   : 9000
```

9. **Network jitter testing** — particularly useful for voice/video troubleshooting.

```python
import subprocess
import re

target = "8.8.8.8"

result = subprocess.run(
    ["ping", "-n", "20", target],
    capture_output=True,
    text=True
)

times = re.findall(
    r"time[=<](\d+)ms",
    result.stdout
)

times = [int(x) for x in times]

if times:

    differences = [
        abs(times[i] - times[i-1])
        for i in range(1, len(times))
    ]

    jitter = sum(differences) / len(differences)

    print("Samples :", times)
    print("Min     :", min(times), "ms")
    print("Max     :", max(times), "ms")
    print("Average :", sum(times)/len(times), "ms")
    print("Jitter  :", round(jitter, 2), "ms")
```

Example:

```text
Samples : [17, 18, 17, 21, 19, 18, 17, 20]

Min     : 17 ms
Max     : 21 ms
Average : 18.4 ms
Jitter  : 1.57 ms
```

10. **Continuous connectivity monitoring** — probably the most practically useful.

```python
import subprocess
from datetime import datetime
import time

target = "8.8.8.8"

while True:

    result = subprocess.run(
        ["ping", "-n", "1", target],
        capture_output=True,
        text=True
    )

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    status = (
        "UP"
        if result.returncode == 0
        else "DOWN"
    )

    print(
        timestamp,
        target,
        status
    )

    time.sleep(5)
```

You can eventually combine these into one **Python Network Diagnostic Tool**:

```text
========================================
       NETWORK PACKET TEST
========================================

Target              : 8.8.8.8

ICMP
----------------------------------------
Reachability         PASS
Packet Loss          0%
Average RTT          18 ms
Jitter               1.4 ms

MTU
----------------------------------------
512 bytes            PASS
1400 bytes           PASS
1472 bytes           PASS
2000 bytes           FAIL
8972 bytes           FAIL

Maximum Payload      1472
Path MTU             1500

TCP
----------------------------------------
TCP/53               PASS
TCP/443              PASS
443 Handshake         19 ms

DNS
----------------------------------------
google.com            PASS
DNS Response          24 ms

PATH
----------------------------------------
Traceroute            PASS
Hops                   9

========================================
Overall Network       HEALTHY
========================================
```

After these, the most interesting next level is **packet capture and protocol analysis with Python**—capturing ICMP/TCP/UDP packets and displaying source/destination IP, ports, TCP flags, TTL, packet length, and timestamps. That pairs very well with Wireshark for learning what is actually happening on the wire.

In [4]:
import socket
import time

host = "8.8.8.8"
port = 53

start = time.perf_counter()

try:
    sock = socket.create_connection(
        (host, port),
        timeout=3
    )

    elapsed = (time.perf_counter() - start) * 1000

    print(f"Target     : {host}")
    print(f"Port       : {port}")
    print("TCP Test   : PASS")
    print(f"Connect RTT: {elapsed:.2f} ms")

    sock.close()

except socket.timeout:
    print("TCP Test   : TIMEOUT")

except ConnectionRefusedError:
    print("TCP Test   : CONNECTION REFUSED")

except OSError as error:
    print("TCP Test   : FAIL")
    print("Error      :", error)

Target     : 8.8.8.8
Port       : 53
TCP Test   : PASS
Connect RTT: 14.12 ms


In [5]:
import socket
import time

host = "8.8.8.8"
port = 53

for sequence in range(1, 11):

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        elapsed = (time.perf_counter() - start) * 1000

        print(
            f"TCP #{sequence}: "
            f"{host}:{port} "
            f"PASS "
            f"{elapsed:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(
            f"TCP #{sequence}: "
            f"{host}:{port} FAIL - {error}"
        )

    time.sleep(1)

TCP #1: 8.8.8.8:53 PASS 12.60 ms
TCP #2: 8.8.8.8:53 PASS 10.67 ms
TCP #3: 8.8.8.8:53 PASS 23.45 ms
TCP #4: 8.8.8.8:53 PASS 16.20 ms
TCP #5: 8.8.8.8:53 PASS 40.04 ms
TCP #6: 8.8.8.8:53 PASS 11.43 ms


KeyboardInterrupt: 

In [6]:
import socket
import time
import statistics

host = "8.8.8.8"
port = 53
tests = 10

results = []

print(f"TCP testing {host}:{port}")
print("-" * 50)

for i in range(1, tests + 1):

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        results.append(latency)

        print(
            f"#{i:<2} PASS   "
            f"{latency:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(f"#{i:<2} FAIL   {error}")

    time.sleep(0.5)


print("\n===== RESULTS =====")

success = len(results)
failed = tests - success

print(f"Sent       : {tests}")
print(f"Successful : {success}")
print(f"Failed     : {failed}")
print(f"Success    : {(success/tests)*100:.1f}%")

if results:

    print(f"Minimum    : {min(results):.2f} ms")
    print(f"Maximum    : {max(results):.2f} ms")
    print(f"Average    : {statistics.mean(results):.2f} ms")

    if len(results) > 1:
        print(f"Std Dev    : {statistics.stdev(results):.2f} ms")

TCP testing 8.8.8.8:53
--------------------------------------------------
#1  PASS   28.90 ms
#2  PASS   14.86 ms
#3  PASS   14.15 ms
#4  PASS   11.48 ms
#5  PASS   11.23 ms
#6  PASS   11.78 ms
#7  PASS   11.92 ms
#8  PASS   33.74 ms
#9  PASS   24.44 ms
#10 PASS   13.91 ms

===== RESULTS =====
Sent       : 10
Successful : 10
Failed     : 0
Success    : 100.0%
Minimum    : 11.23 ms
Maximum    : 33.74 ms
Average    : 17.64 ms
Std Dev    : 8.25 ms


In [7]:
import socket
import time

targets = [
    ("8.8.8.8", 53, "Google DNS"),
    ("1.1.1.1", 53, "Cloudflare DNS"),
    ("google.com", 443, "Google HTTPS"),
    ("microsoft.com", 443, "Microsoft HTTPS"),
    ("github.com", 443, "GitHub HTTPS"),
]

print(
    f"{'TARGET':<20}"
    f"{'PORT':<8}"
    f"{'SERVICE':<20}"
    f"{'STATUS':<10}"
    f"{'TIME'}"
)

print("-" * 75)

for host, port, service in targets:

    start = time.perf_counter()

    try:

        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        print(
            f"{host:<20}"
            f"{port:<8}"
            f"{service:<20}"
            f"{'PASS':<10}"
            f"{latency:.2f} ms"
        )

        sock.close()

    except Exception:
        print(
            f"{host:<20}"
            f"{port:<8}"
            f"{service:<20}"
            f"{'FAIL':<10}"
        )

TARGET              PORT    SERVICE             STATUS    TIME
---------------------------------------------------------------------------
8.8.8.8             53      Google DNS          PASS      36.57 ms
1.1.1.1             53      Cloudflare DNS      PASS      16.67 ms
google.com          443     Google HTTPS        PASS      6.29 ms
microsoft.com       443     Microsoft HTTPS     PASS      21.56 ms
github.com          443     GitHub HTTPS        PASS      32.53 ms


In [8]:
import socket

target = "192.168.32.128"

ports = {
    22: "SSH",
    80: "HTTP",
    443: "HTTPS",
}

for port, service in ports.items():

    try:
        connection = socket.create_connection(
            (target, port),
            timeout=2
        )

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"REACHABLE"
        )

        connection.close()

    except ConnectionRefusedError:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"REFUSED"
        )

    except socket.timeout:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"TIMEOUT"
        )

    except OSError as error:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"ERROR: {error}"
        )

22     SSH        REACHABLE
80     HTTP       REACHABLE
443    HTTPS      TIMEOUT


In [9]:
import subprocess
import socket
import time

host = "8.8.8.8"
port = 53

print("===== ICMP TEST =====")

icmp = subprocess.run(
    ["ping", "-n", "2", host],
    capture_output=True,
    text=True
)

if icmp.returncode == 0:
    print("ICMP : PASS")
else:
    print("ICMP : FAIL")


print("\n===== TCP TEST =====")

start = time.perf_counter()

try:

    sock = socket.create_connection(
        (host, port),
        timeout=3
    )

    latency = (time.perf_counter() - start) * 1000

    print("TCP  : PASS")
    print(f"Port : {port}")
    print(f"Time : {latency:.2f} ms")

    sock.close()

except Exception as error:

    print("TCP  : FAIL")
    print(error)

===== ICMP TEST =====
ICMP : FAIL

===== TCP TEST =====
TCP  : PASS
Port : 53
Time : 17.60 ms


In [10]:
import socket
import time

hostname = "google.com"
port = 443

print("===== DNS =====")

start = time.perf_counter()

ip = socket.gethostbyname(hostname)

dns_time = (time.perf_counter() - start) * 1000

print("Hostname :", hostname)
print("IP       :", ip)
print(f"DNS Time : {dns_time:.2f} ms")


print("\n===== TCP =====")

start = time.perf_counter()

sock = socket.create_connection(
    (ip, port),
    timeout=3
)

tcp_time = (time.perf_counter() - start) * 1000

print("Port     :", port)
print("Status   : PASS")
print(f"TCP Time : {tcp_time:.2f} ms")

sock.close()

===== DNS =====
Hostname : google.com
IP       : 142.251.34.206
DNS Time : 6.67 ms

===== TCP =====
Port     : 443
Status   : PASS
TCP Time : 17.06 ms


In [11]:
import socket
import ssl
import time

hostname = "google.com"
port = 443

context = ssl.create_default_context()

start = time.perf_counter()

with socket.create_connection(
    (hostname, port),
    timeout=5
) as sock:

    tcp_time = (
        time.perf_counter() - start
    ) * 1000

    tls_start = time.perf_counter()

    with context.wrap_socket(
        sock,
        server_hostname=hostname
    ) as secure_socket:

        tls_time = (
            time.perf_counter() - tls_start
        ) * 1000

        print("TCP Connection : PASS")
        print(f"TCP Time       : {tcp_time:.2f} ms")

        print("TLS Handshake  : PASS")
        print(f"TLS Time       : {tls_time:.2f} ms")

        print(
            "TLS Version    :",
            secure_socket.version()
        )

TCP Connection : PASS
TCP Time       : 6.65 ms
TLS Handshake  : PASS
TLS Time       : 91.28 ms
TLS Version    : TLSv1.3


Yes. TCP testing with Python is very useful because it tells you more than ICMP ping: **DNS resolution, TCP reachability, port state, connection time, repeated reliability, and application-level response**.

One important point: `8.8.8.8` is Google's public DNS service. **TCP port 53** is the most meaningful TCP test for that IP. Don't assume ports like 80 or 443 will be open just because the host responds to ICMP.

## 1. Basic TCP "ping" to 8.8.8.8:53

```python
import socket
import time

host = "8.8.8.8"
port = 53

start = time.perf_counter()

try:
    sock = socket.create_connection(
        (host, port),
        timeout=3
    )

    elapsed = (time.perf_counter() - start) * 1000

    print(f"Target     : {host}")
    print(f"Port       : {port}")
    print("TCP Test   : PASS")
    print(f"Connect RTT: {elapsed:.2f} ms")

    sock.close()

except socket.timeout:
    print("TCP Test   : TIMEOUT")

except ConnectionRefusedError:
    print("TCP Test   : CONNECTION REFUSED")

except OSError as error:
    print("TCP Test   : FAIL")
    print("Error      :", error)
```

Example:

```text
Target     : 8.8.8.8
Port       : 53
TCP Test   : PASS
Connect RTT: 17.84 ms
```

That connection time roughly measures how long it took to establish the TCP connection.

---

## 2. Repeated TCP ping

This is much more useful for monitoring.

```python
import socket
import time

host = "8.8.8.8"
port = 53

for sequence in range(1, 11):

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        elapsed = (time.perf_counter() - start) * 1000

        print(
            f"TCP #{sequence}: "
            f"{host}:{port} "
            f"PASS "
            f"{elapsed:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(
            f"TCP #{sequence}: "
            f"{host}:{port} FAIL - {error}"
        )

    time.sleep(1)
```

You might see:

```text
TCP #1: 8.8.8.8:53 PASS 17.42 ms
TCP #2: 8.8.8.8:53 PASS 16.91 ms
TCP #3: 8.8.8.8:53 PASS 18.21 ms
TCP #4: 8.8.8.8:53 PASS 17.05 ms
TCP #5: 8.8.8.8:53 PASS 21.33 ms
```

---

## 3. Calculate TCP success rate and latency

This starts behaving like an actual TCP-ping utility.

```python
import socket
import time
import statistics

host = "8.8.8.8"
port = 53
tests = 10

results = []

print(f"TCP testing {host}:{port}")
print("-" * 50)

for i in range(1, tests + 1):

    start = time.perf_counter()

    try:
        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        results.append(latency)

        print(
            f"#{i:<2} PASS   "
            f"{latency:.2f} ms"
        )

        sock.close()

    except Exception as error:
        print(f"#{i:<2} FAIL   {error}")

    time.sleep(0.5)


print("\n===== RESULTS =====")

success = len(results)
failed = tests - success

print(f"Sent       : {tests}")
print(f"Successful : {success}")
print(f"Failed     : {failed}")
print(f"Success    : {(success/tests)*100:.1f}%")

if results:

    print(f"Minimum    : {min(results):.2f} ms")
    print(f"Maximum    : {max(results):.2f} ms")
    print(f"Average    : {statistics.mean(results):.2f} ms")

    if len(results) > 1:
        print(f"Std Dev    : {statistics.stdev(results):.2f} ms")
```

Example:

```text
TCP testing 8.8.8.8:53
--------------------------------------------------
#1  PASS   17.21 ms
#2  PASS   16.89 ms
#3  PASS   18.42 ms
#4  PASS   17.52 ms
#5  PASS   20.13 ms
#6  PASS   17.01 ms
#7  PASS   18.33 ms
#8  PASS   16.72 ms
#9  PASS   17.84 ms
#10 PASS   18.01 ms

===== RESULTS =====
Sent       : 10
Successful : 10
Failed     : 0
Success    : 100.0%
Minimum    : 16.72 ms
Maximum    : 20.13 ms
Average    : 17.81 ms
Std Dev    : 0.98 ms
```

## 4. Test multiple hosts and known service ports

Instead of testing random ports, test ports appropriate to services you expect to be reachable.

```python
import socket
import time

targets = [
    ("8.8.8.8", 53, "Google DNS"),
    ("1.1.1.1", 53, "Cloudflare DNS"),
    ("google.com", 443, "Google HTTPS"),
    ("microsoft.com", 443, "Microsoft HTTPS"),
    ("github.com", 443, "GitHub HTTPS"),
]

print(
    f"{'TARGET':<20}"
    f"{'PORT':<8}"
    f"{'SERVICE':<20}"
    f"{'STATUS':<10}"
    f"{'TIME'}"
)

print("-" * 75)

for host, port, service in targets:

    start = time.perf_counter()

    try:

        sock = socket.create_connection(
            (host, port),
            timeout=3
        )

        latency = (time.perf_counter() - start) * 1000

        print(
            f"{host:<20}"
            f"{port:<8}"
            f"{service:<20}"
            f"{'PASS':<10}"
            f"{latency:.2f} ms"
        )

        sock.close()

    except Exception:
        print(
            f"{host:<20}"
            f"{port:<8}"
            f"{service:<20}"
            f"{'FAIL':<10}"
        )
```

## 5. Test ports on your own server

For a machine you administer, you can check expected services:

```python
import socket

target = "192.168.32.128"

ports = {
    22: "SSH",
    80: "HTTP",
    443: "HTTPS",
}

for port, service in ports.items():

    try:
        connection = socket.create_connection(
            (target, port),
            timeout=2
        )

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"REACHABLE"
        )

        connection.close()

    except ConnectionRefusedError:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"REFUSED"
        )

    except socket.timeout:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"TIMEOUT"
        )

    except OSError as error:

        print(
            f"{port:<6} "
            f"{service:<10} "
            f"ERROR: {error}"
        )
```

The distinction is important:

```text
REACHABLE
    TCP connection succeeded.

REFUSED
    Host responded, but nothing is accepting TCP
    connections on that port.

TIMEOUT
    No TCP response was received before timeout.
    A firewall/filter or network problem is one
    possible cause.

ERROR
    Some other socket/network error occurred.
```

A timeout alone does **not** prove a firewall is responsible.

## 6. Compare ICMP ping with TCP

This is an excellent troubleshooting test.

```python
import subprocess
import socket
import time

host = "8.8.8.8"
port = 53

print("===== ICMP TEST =====")

icmp = subprocess.run(
    ["ping", "-n", "2", host],
    capture_output=True,
    text=True
)

if icmp.returncode == 0:
    print("ICMP : PASS")
else:
    print("ICMP : FAIL")


print("\n===== TCP TEST =====")

start = time.perf_counter()

try:

    sock = socket.create_connection(
        (host, port),
        timeout=3
    )

    latency = (time.perf_counter() - start) * 1000

    print("TCP  : PASS")
    print(f"Port : {port}")
    print(f"Time : {latency:.2f} ms")

    sock.close()

except Exception as error:

    print("TCP  : FAIL")
    print(error)
```

This gives you four interesting troubleshooting scenarios:

```text
ICMP PASS + TCP PASS
Host reachable and TCP service reachable.

ICMP PASS + TCP FAIL
Host reachable, but service/port isn't reachable.

ICMP FAIL + TCP PASS
ICMP may be filtered while the application works.

ICMP FAIL + TCP FAIL
Could be routing, firewall, destination, or other
connectivity problems.
```

## 7. DNS + TCP test

A hostname connection actually involves multiple stages:

```text
google.com
    |
    +--- DNS resolution
    |
    +--- Destination IP
    |
    +--- TCP connection
    |
    +--- Application protocol
```

You can measure DNS and TCP separately:

```python
import socket
import time

hostname = "google.com"
port = 443

print("===== DNS =====")

start = time.perf_counter()

ip = socket.gethostbyname(hostname)

dns_time = (time.perf_counter() - start) * 1000

print("Hostname :", hostname)
print("IP       :", ip)
print(f"DNS Time : {dns_time:.2f} ms")


print("\n===== TCP =====")

start = time.perf_counter()

sock = socket.create_connection(
    (ip, port),
    timeout=3
)

tcp_time = (time.perf_counter() - start) * 1000

print("Port     :", port)
print("Status   : PASS")
print(f"TCP Time : {tcp_time:.2f} ms")

sock.close()
```

This helps distinguish:

```text
DNS slow?
      ↓
TCP connection slow?
      ↓
Application slow?
```

## 8. Test the actual HTTPS connection

TCP/443 succeeding only proves that the TCP endpoint accepted a connection. You can go one level higher and test TLS:

```python
import socket
import ssl
import time

hostname = "google.com"
port = 443

context = ssl.create_default_context()

start = time.perf_counter()

with socket.create_connection(
    (hostname, port),
    timeout=5
) as sock:

    tcp_time = (
        time.perf_counter() - start
    ) * 1000

    tls_start = time.perf_counter()

    with context.wrap_socket(
        sock,
        server_hostname=hostname
    ) as secure_socket:

        tls_time = (
            time.perf_counter() - tls_start
        ) * 1000

        print("TCP Connection : PASS")
        print(f"TCP Time       : {tcp_time:.2f} ms")

        print("TLS Handshake  : PASS")
        print(f"TLS Time       : {tls_time:.2f} ms")

        print(
            "TLS Version    :",
            secure_socket.version()
        )
```

Example:

```text
TCP Connection : PASS
TCP Time       : 18.31 ms
TLS Handshake  : PASS
TLS Time       : 32.48 ms
TLS Version    : TLSv1.3
```

This is a much better real-world troubleshooting sequence:

```text
PC
 │
 ├── DNS resolution
 │
 ├── IP reachability
 │
 ├── TCP SYN
 │      ↓
 │   SYN-ACK
 │      ↓
 │     ACK
 │
 ├── TLS handshake
 │
 └── HTTPS request
```

For network-engineering practice, I'd work through **ICMP → DNS → TCP connection → TCP latency → TLS handshake → HTTP response**. That mirrors how you would isolate whether a real application connectivity problem is at the network, transport, TLS, or application layer.